/*
 * iav_config.h
 *
 * History:
 *	2021/04/06 - [Zhaoyang Chen] modified file
 *
 * Copyright (c) 2021 Ambarella, Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __IAV_CONFIG_H__
#define __IAV_CONFIG_H__

#ifdef AMBA_AMYOC_BUILD
#include <ambvideo_conf.h>
#endif
#include <amba_arch_mem.h>
#include <iav_ioctl.h>
#include "dsp_cmd_msg.h"

/************************************************
 *
 * Following definitions can be modified.
 * They are software limitations based on different
 * NAND size and memory configurations.
 *
 ***********************************************/


/************************************************
 *
 * Following definitions CANNOT be modified !!
 * They are HW limitations !!
 *
 ***********************************************/

/*
 * Basic configuration
 */
#define PIXEL_IN_MB							(16)
#define PIXEL_IN_CTB						(32)
#define POSTP_MAIN_EXT_BUF_V_ALIGN			(32)
#define HEVC_STREAM_H_ALIGNMENT				(8)
#define MAX_STR_DUMMY_LATENCY				(4)
#define DUAL_CORE_SPATIAL_H_ALIGNMENT		(32)
#define FRAME_SIZE_UNIT						(32)
#define HALF_SECOND_IN_MS					(500)
#define TWO_SECOND_IN_MS					(2000)
#define FIVE_SECOND_IN_MS					(5000)
#define FIFTEEN_SECOND_IN_MS				(15000)
#define TWO_SECONDS_IN_HZ					(msecs_to_jiffies(2000))
#define FIVE_SECONDS_IN_HZ					(msecs_to_jiffies(5000))
#define INVALID_DSP_PTS_32					(0xFFFFFFFF)
#define ENCODE_DURATION_FOREVER				(0xFFFFFFFF)
#define NS_IN_ONE_SECOND					(1000000000u)
#define DSP_DRAM_PRI_DEFAULT				(0xF)
#define DSP_DRAM_PRI_MAX					(1)

#define IAV_MIN_EXT_BUF_NUM					(4)
#define IAV_EXT_BUF_NUM_MARGIN				(5)

#define IAV_MAX_MF_BUF_NUM					(80)
#define IAV_MF_WAIT_TIMEOUT					(16)	/* Used for irq tick count */
#define IAV_EXT_MEM_PADDING					(16)
#define IAV_INT_MEM_PADDING					(8)
#define IAV_RAW_FEED_MIN_DSP_HOLD_NUM		(3)
#define IAV_H26X_MAX_SLICE_NUM				(16)

#define IAV_MAX_STAGING_BUF_NUM   (15)  /* ucode has 4 bits for staging buffer number */
#define IAV_DEFAULT_POSTP_BUF_NUM (6)
#define IAV_DEFAULT_BUF_NUM (4)
#define IAV_AISP_BUF_NUM (10)
#define IAV_MCTF_CMPR_EXTRA_BUF_NUM (3)
#define IAV_EFM_PER_CHAN_CANVAS_NUM (7)

#define IAV_MAX_ARB_BLEND_WIDTH 	OVERLAY_AREA_MAX_WIDTH
#define IAV_ARB_BLEND_WIDTH_ALIGN	(64)
#define IAV_ARB_BLEND_HEIGHT_ALIGN	(16)

#if defined(AMBA_SOC_CV75)
#define MAX_WIDTH_IN_FULL_FPS				(1216)
#else
#define MAX_WIDTH_IN_FULL_FPS				(2048)
#endif
#define SRCBUF_LINE_BUFFER_WIDTH			(2048)

#define RAW_PADDING_ALIGN					(32)
#define IAV_MAX_VPROC_MIXER_WIDTH			(2048)

#define IAV_MAX_IDSP_TIMEOUT_IN_MS			(128)
#define IAV_MAX_VP_TIMEOUT_IN_MS			(128)

#define IAV_MIN_BSB_SIZE					(0x100000)	/* 1MB */
#define IAV_BSB_SIZE_ALIGN					(0x10000)	/* 64KB */
#define IAV_SINGLE_STREAM_BSB_SIZE_MIN		(0x80000)	/* 0.5MB */
#define IAV_SINGLE_STREAM_BSB_SIZE_ALIGN	(0x1000)	/* 4KB */

#define IAV_FUSION_MAIN_OUT_WIDTH_ALIGN		(32)
#define IAV_FUSION_MAIN_OUT_HEIGHT_ALIGN		(16)

#define IAV_DEFAULT_HEART_BEAT_INTVAL_MS (1000)
#define IAV_MAX_HEART_BEAT_INTVAL_MS	(10000)
#define IAV_HEART_BEAT_INTVAL_UNIT_MS	(50)
#define IAV_HEART_BEAT_TIMEOUT_THRESHOLD_MULTI	(3)

#define IAV_MAX_STR_LEN			(256)

#define IAV_VERT_OFFSET_IN_RAW_ALIGN		(2)

/*
 * YUV format size alignment (chroma subsample).
 * YUV400 has no width / height alignment requirement.
 */
#define IAV_YUV420_WIDTH_ALIGN	(2)
#define IAV_YUV420_HEIGHT_ALIGN	(2)
#define IAV_YUV422_WIDTH_ALIGN	(2)

/* IDSP job queue size calculation formula for v-effect module:
 * max_job_queue_size = (tile_num * chan_num + copy num + blend num) * buffered_frame_num
 * buffered_frame_num is hardcoded to 3 by default in ucode
 * Examples:
 * 1. 4x4k vin -> 4x4k chan -> horizontal stitching
 * (4 * 4 + 3 + 3) * 3 = 66
 * 2. 8x4M vin -> 8x4M chan -> horizontal stitching
 * (2 * 8 + 7 + 7) * 3 = 90
 */
#define IAV_MAX_IDSP_JOB_QUEUE_SIZE			(128)
#define IAV_SOF_EOF_PTS_QUEUE_DEPTH			(5)
#define PTS_OVERFLOW_THRESHOLD				(1 << 28)
#define IAV_VOUT_DEF_INTERNAL_Q_DEPTH		(2)
#define IAV_VOUT_DEF_BOOT_INTERNAL_Q_DEPTH	(8)
#define IAV_VOUT_MAX_INTERNAL_Q_DEPTH		(15)
#define IAV_VOUT_BUF_BASE_NUM 				(2)
#define IAV_VOUT_BUF_NUM 					(IAV_VOUT_DEF_INTERNAL_Q_DEPTH + IAV_VOUT_BUF_BASE_NUM + 1)

#if defined(AMBA_SOC_CV75) || defined(AMBA_SOC_N1_655)
#define IAV_MAX_VOUT_NUM					(1)
#else
#define IAV_MAX_VOUT_NUM					(3)
#endif

#define MAX_VIN_NUM_FOR_DOUBLE_BANK			(6)

#define IAV_VIN_HDS_MAX_WIDTH			(2048)

#define IAV_VIN_SLICE_V_ALIGN			(2)

#define IAV_VIN_DBUF_CFG_SIZE_ALIGN		(4)

#define ISO_RETIRE_FRAMES_MAX  			(120)

/* burst tile alignment */
#define IAV_BURST_TILE_OFFSET_ALIGN		(16)
#define IAV_BURST_TILE_WIDTH_ALIGN		(16)
#define IAV_BURST_TILE_HEIGHT_ALIGN		(8)

#define CHROMA_WAIT_LINE_1A_PASS		(28)

#define IAV_POSTP_HSK_INTVL_DEFAULT		(2)
#define IAV_POSTP_HSK_INTVL_MAX			(7)

/*
 * VP configuration
 */
#define DSP_VP_MSG_SIZE			(512)
#define VP_MSG_INFO_SIZE		(128)
#define DSP_VP_MSG_NUM			(128)


typedef enum {
	IMG_CMD_SIZE = DSP_CMD_SIZE,

	IMG_BATCH_LISO_CMD_PER_PART = 5,
	IMG_BATCH_LISO_CMD_PART_SIZE = (IMG_CMD_SIZE * IMG_BATCH_LISO_CMD_PER_PART),
	IMG_BATCH_LISO_CMD_TOGGLE_NUM = 16,
	IMG_BATCH_LISO_CMD_TOTAL_SIZE = (IMG_BATCH_LISO_CMD_PART_SIZE *
		IMG_BATCH_LISO_CMD_TOGGLE_NUM * CONFIG_AMBARELLA_MAX_CHANNEL_NUM),

	IMG_BATCH_DEBUG_CMD_PER_PART = 2,
	IMG_BATCH_DEBUG_CMD_PART_SIZE = (IMG_CMD_SIZE * IMG_BATCH_DEBUG_CMD_PER_PART),
	IMG_BATCH_DEBUG_CMD_TOGGLE_NUM = 8,
	IMG_BATCH_DEBUG_CMD_TOTAL_SIZE = (IMG_BATCH_DEBUG_CMD_PART_SIZE *
		IMG_BATCH_DEBUG_CMD_TOGGLE_NUM * CONFIG_AMBARELLA_MAX_CHANNEL_NUM),

	/* 3A statistics data PARAM, and each AAA BUF size is 62KB. */
	AAA_BUF_NUM_DEF = 32,
} IMG_PARAMS;

#define MAX_AUDIO_CLK_KHZ					(12288)
#define MIN_AUDIO_CLK_KHZ					(1000)
#define MSEC_UNIT_TICKS						(MAX_AUDIO_CLK_KHZ)
#define PTS_CLK								(90000)

#define KByte(x)							((x) << 10)
#define MByte(x)							((x) << 20)
#define MByte_16(x)							((x) << 24)

/*
 * Decode configuration
 */
#define MAX_DEC_NUM_WITH_ENC	(10)
#define MAX_DEC_WIDTH	(8192)
#define MAX_DEC_HEIGHT	(15360)
#define MAX_DECODER_CHAN_NUM 	(4)	/* max 4 decoder channels per decoder */

/*
 * Encode configuration
 */
#define IAV_MAX_ENCODE_STREAMS_NUM			(IAV_STREAM_MAX_NUM_ALL)
#define IAV_INIT_ENCODE_STREAMS_NUM			(4)
#define IAV_MAX_EFM_STREAM_NUM				(8)
#define IAV_MAX_STATIS_NUM					(8)
#define STREAM_ID_MASK						((1ULL << IAV_MAX_ENCODE_STREAMS_NUM) - 1)
#define IAV_MAX_ENCODE_BITRATE				(32 * IAV_MAX_ENCODE_STREAMS_NUM * MB)
#define HEVC_CTB_HEIGHT						(32)
#define HEVC_CTB_WIDTH						(32)
#define IAV_MAX_H26X_ENCODE_WIDTH			(11648)
#define IAV_MAX_H26X_ENCODE_HEIGHT			(8192)
#define IAV_MAX_IMG_SCALE_INPUT_WIDTH		(14336)
#define IAV_MAX_IMG_SCALE_INPUT_HEIGHT		(14336)
#define IAV_MAX_IMG_SCALE_OUTPUT_WIDTH		(14336)
#define IAV_MAX_IMG_SCALE_OUTPUT_HEIGHT		(8192)
#define H26X_DEFAULT_SKIP_STRENGTH		(2)
#define H265_DEFAULT_CU8_BIAS_LEVEL		(4)
#define IAV_ENC_EXTRA_PADDING_PIXELS		(16)
#define IAV_MAX_EFM_REL_BUF_NUM			(128)
#define IAV_MIN_ENC_WIDTH_IN_STREAM		(160)
#define IAV_MIN_ENC_HEIGHT_IN_STREAM		(90)
#define IAV_MAX_SMVMAX_VAL		(128)

typedef enum {
	IAV_PJPEG_WIDTH_SMALL = 1920,
	IAV_PJPEG_WIDTH_MEDIUM = 2592,
	IAV_PJPEG_WIDTH_LARGE = 3840,
	IAV_PJPEG_WIDTH_HUGE = 7680,

	IAV_PJPEG_HEIGHT_SMALL = 1080,
	IAV_PJPEG_HEIGHT_MEDIUM = 1952,
	IAV_PJPEG_HEIGHT_LARGE = 2160,
	IAV_PJPEG_HEIGHT_HUGE = 4320,

	IAV_HEVC_PJPEG_MB_SMALL = 2,
	IAV_HEVC_PJPEG_MB_MEDIUM = 3,
	IAV_HEVC_PJPEG_MB_LARGE = 4,
	IAV_HEVC_PJPEG_MB_HUGE = 8,

	IAV_AVC_PJPEG_MB_SMALL = 4,
	IAV_AVC_PJPEG_MB_MEDIUM = 5,
	IAV_AVC_PJPEG_MB_LARGE = 6,
	IAV_AVC_PJPEG_MB_HUGE = 12,

	IAV_MJPEG_PJPEG_MB_SMALL = 6,
	IAV_MJPEG_PJPEG_MB_MEDIUM = 12,
	IAV_MJPEG_PJPEG_MB_LARGE = 16,
	IAV_MJPEG_PJPEG_MB_HUGE = 64,

	IAV_PJPEG_MB_MAX = 64,
} IAV_PJPEG_PARAM;

typedef enum {
	IAV_AISP_INPUT_WIDTH_1920 = 1920,
	IAV_AISP_INPUT_WIDTH_4K = 3840,
	IAV_AISP_TILE_WIDTH = 1024,
	IAV_AISP_OVERLAP_WIDTH = 64,
} IAV_AISP_INPUT_WIDTH;

#define IAV_PJPEG_SIZE_SMALL		((IAV_PJPEG_WIDTH_SMALL) * (IAV_PJPEG_HEIGHT_SMALL))
#define IAV_PJPEG_SIZE_MEDIUM		((IAV_PJPEG_WIDTH_MEDIUM) * (IAV_PJPEG_HEIGHT_MEDIUM))
#define IAV_PJPEG_SIZE_LARGE		((IAV_PJPEG_WIDTH_LARGE) * (IAV_PJPEG_HEIGHT_LARGE))
#define IAV_PJPEG_SIZE_HUGE			((IAV_PJPEG_WIDTH_HUGE) * (IAV_PJPEG_HEIGHT_HUGE))

typedef enum {
	FAST_SEEK_INTVL_MAX = 63,
	MAX_REF_FRAME_INTVL = 3,
	MAX_ZMV_THRESHOLD = 255,
	MIN_INTRABIAS = 1,
	MAX_INTRABIAS = 4000,
	MIN_USER_BIAS = 0,
	MAX_USER_BIAS = 0xFFFF,
	MAX_FRAME_DROP_COUNT = 255,
	MAX_FRAME_TRIGGER_COUNT = 255,
	MAX_PSKIP_REPEAT = 254,
	MAX_SKIP_STRENGTH = 4,

	/* BIAS PARAM */
	H264_BIAS_MODE_ADD = 0,
	H264_BIAS_MODE_OVERRIDE = 1,

	/* RC PARAM */
	H264_RC_CONST_QP = 37,
	H265_RC_CONST_QP = 37,

	/* QP ROI PARAM */
	ROI_CATEGORY_MIN = 0,
	ROI_CATEGORY_MAX_HEVC = 7,
	ROI_CATEGORY_MAX_AVC = 3,
	ROI_QP_ADJUST_MIN = -51,
	ROI_QP_ADJUST_MAX = 51,
} IAV_ENC_CFG_PARAM;

typedef enum {
	IAV_EXTRA_DRAM_BUF_DEFAULT = 0,
	IAV_EXTRA_DRAM_BUF_MIN = -1,
	IAV_EXTRA_DRAM_BUF_MAX = 7,
} IAV_EXTRA_DRAM_BUF;

/*
 * H26X Scalelist Memory Configuration
 * */
typedef enum {
#ifdef CONFIG_AMBARELLA_IAV_H26X_SCALELIST
	SINGLE_H26X_SCALELIST_BUFFER_SIZE = (1 << 10),
#else
	SINGLE_H26X_SCALELIST_BUFFER_SIZE = 0,
#endif
	H26X_SCALELIST_BUFFER_SIZE = SINGLE_H26X_SCALELIST_BUFFER_SIZE * IAV_MAX_ENCODE_STREAMS_NUM,
} IAV_HEVC_SCALELIST_PARAMS;

/*
 * IDSP performance load
 */
typedef enum {
	/* IDSP performance in MB unit:
	 * 592920 = (2592/16) * (1952/16) * 30
	 * 734400 = (1920/16) * (1088/16) * 90
	 * 972000 = (3840/16) * (2160/16) * 30
	 * 979200 = (1920/16) * (1088/16) * 120
	 * 1296000 = (3840/16) * (2160/16) * 40
	 * 1468800 = (1920/16) * (1088/16) * 180
	 * 1944000 = (3840/16) * (2160/16) * 60
	 * 1958400 = (1920/16) * (1088/16) * 240
	 * 2422800 = (3840/16) * (2160/16) * 60 + (2688/16) * (1520/16) *30
	 * 2430000 = (3840/16) * (2160/16) * 75
	 * 2448000 = (1920/16) * (1088/16) * 300
	 * 2592000 = (3840/16) * (2160/16) * 80
	 * 2916000 = (3840/16) * (2160/16) * 90
	 * 3240000 = (3840/16) * (2160/16) * 100
	 * 3888000 = (3840/16) * (2160/16) * 120
	 * 4860000 = (3840/16) * (2160/16) * 150
	 * 5832000 = (3840/16) * (2160/16) * 180
	 * 6804000 = (3840/16) * (2160/16) * 210
	 * 7776000 = (3840/16) * (2160/16) * 240
	 */
	IDSP_LOAD_5MP30 = (2592 * 1952 / 256 * 30),
	IDSP_LOAD_6MP30 = (1920 * 1088 / 256 * 90),
	IDSP_LOAD_4KP30 = (3840 * 2160 / 256 * 30),
	IDSP_LOAD_8MP30 = (1920 * 1088 / 256 * 120),
	IDSP_LOAD_4KP40 = (3840 * 2160 / 256 * 40),
	IDSP_LOAD_8MP45 = (1920 * 1088 / 256 * 180),
	IDSP_LOAD_4KP60 = (3840 * 2160 / 256 * 60),
	IDSP_LOAD_8MP60 = (1920 * 1088 / 256 * 240),
	IDSP_LOAD_4KP60_4MP30 = (3840 * 2160 / 256 * 60 + 2688 * 1520 / 256 *30),
	IDSP_LOAD_4KP75 = (3840 * 2160 / 256 * 75),
	IDSP_LOAD_8MP75 = (1920 * 1088 / 256 * 300),
	IDSP_LOAD_4KP80 = (3840 * 2160 / 256 * 80),
	IDSP_LOAD_4KP90 = (3840 * 2160 / 256 * 90),
	IDSP_LOAD_4KP100 = (3840 * 2160 / 256 * 100),
	IDSP_LOAD_4KP120 = (3840 * 2160 / 256 * 120),
	IDSP_LOAD_4KP150 = (3840 * 2160 / 256 * 150),
	IDSP_LOAD_4KP180 = (3840 * 2160 / 256 * 180),
	IDSP_LOAD_4KP210 = (3840 * 2160 / 256 * 210),
	IDSP_LOAD_4KP240 = (3840 * 2160 / 256 * 240),

	/* CV5 chip*/
	SYS_IDSP_LOAD_CV5_66 = IDSP_LOAD_4KP100,
	SYS_IDSP_LOAD_CV5_88 = IDSP_LOAD_4KP120,
	SYS_IDSP_LOAD_CV5_99 = IDSP_LOAD_4KP240,
	/* CV52 chip*/
	SYS_IDSP_LOAD_CV52_33 = IDSP_LOAD_4KP60,
	SYS_IDSP_LOAD_CV52_66 = IDSP_LOAD_4KP80,
	SYS_IDSP_LOAD_CV52_99 = IDSP_LOAD_4KP120,

	/* CV72 chip*/
	SYS_IDSP_LOAD_CV72_33 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV72_66 = IDSP_LOAD_8MP75,
	SYS_IDSP_LOAD_CV72_66IQ = IDSP_LOAD_8MP75,
	SYS_IDSP_LOAD_CV72_88 = IDSP_LOAD_8MP75,
	SYS_IDSP_LOAD_CV72_88IQ = IDSP_LOAD_8MP75,
	SYS_IDSP_LOAD_CV72_99 = IDSP_LOAD_4KP120,

	SYS_IDSP_LOAD_CV72AX_36 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV72AX_56 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV72AX_76 = IDSP_LOAD_8MP30 * 3,
	SYS_IDSP_LOAD_CV72AX_86 = IDSP_LOAD_8MP30 * 3,
	SYS_IDSP_LOAD_CV72AQ_56 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV72AQ_76 = IDSP_LOAD_8MP30 * 3,
	SYS_IDSP_LOAD_CV72AQ_86 = IDSP_LOAD_8MP30 * 3,

	/* N1 chip*/
	SYS_IDSP_LOAD_N1_99 = IDSP_LOAD_4KP240,

	/* N1 655 chip*/
	SYS_IDSP_LOAD_N1_655_99 = IDSP_LOAD_4KP120,

	/* CV75 chip*/
	SYS_IDSP_LOAD_CV75_33 = IDSP_LOAD_5MP30,
	SYS_IDSP_LOAD_CV75_33EX = IDSP_LOAD_5MP30,
	SYS_IDSP_LOAD_CV75_66 = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75_68EX = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75_88 = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75_98 = IDSP_LOAD_8MP60,
	SYS_IDSP_LOAD_CV75_99 = IDSP_LOAD_8MP60,
	SYS_IDSP_LOAD_CV75_33M = IDSP_LOAD_5MP30,
	SYS_IDSP_LOAD_CV75_55M = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75_88M = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75_99M = IDSP_LOAD_8MP30,

	SYS_IDSP_LOAD_CV75A_56 = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75A_76 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV75A_96 = IDSP_LOAD_4KP60_4MP30,
	SYS_IDSP_LOAD_CV75A_56M = IDSP_LOAD_6MP30,
	SYS_IDSP_LOAD_CV75AX_56 = IDSP_LOAD_8MP30,
	SYS_IDSP_LOAD_CV75AX_76 = IDSP_LOAD_8MP30 * 2,
	SYS_IDSP_LOAD_CV75AX_56M = IDSP_LOAD_6MP30,
	SYS_IDSP_LOAD_CV75AQ_56 = IDSP_LOAD_6MP30,
	SYS_IDSP_LOAD_CV75AQ_76 = IDSP_LOAD_8MP45,

	/* CV7 chip*/
	SYS_IDSP_LOAD_CV7_66 = IDSP_LOAD_4KP120,
	SYS_IDSP_LOAD_CV7_66IQ = IDSP_LOAD_4KP120,
	SYS_IDSP_LOAD_CV7_88 = IDSP_LOAD_4KP240,
	SYS_IDSP_LOAD_CV7_88IQ = IDSP_LOAD_4KP240,
	SYS_IDSP_LOAD_CV7_99 = IDSP_LOAD_4KP240,
	SYS_IDSP_LOAD_CV7_55M = IDSP_LOAD_4KP90,
	SYS_IDSP_LOAD_CV7_66M = IDSP_LOAD_4KP90,
	SYS_IDSP_LOAD_CV7_99M = IDSP_LOAD_4KP90,
	SYS_IDSP_LOAD_CV7A_56 = IDSP_LOAD_4KP150,
	SYS_IDSP_LOAD_CV7A_76 = IDSP_LOAD_4KP180,
	SYS_IDSP_LOAD_CV7A_86 = IDSP_LOAD_4KP210,
	SYS_IDSP_LOAD_CV7A_56M = IDSP_LOAD_4KP90,
	SYS_IDSP_LOAD_CV7A_76M = IDSP_LOAD_4KP120,
	SYS_IDSP_LOAD_CV7AX_56 = IDSP_LOAD_4KP150,
	SYS_IDSP_LOAD_CV7AX_76 = IDSP_LOAD_4KP180,
	SYS_IDSP_LOAD_CV7AX_86 = IDSP_LOAD_4KP210,
	SYS_IDSP_LOAD_CV7AX_56M = IDSP_LOAD_4KP90,
	SYS_IDSP_LOAD_CV7AX_76M = IDSP_LOAD_4KP120,

	/* CV8 chip*/
	SYS_IDSP_LOAD_CV8_99 = IDSP_LOAD_4KP240,
} IAV_SYS_IDSP_LOAD;

/*
 * Encode performance load
 */
typedef enum {
	/* Encode performance in MB unit:
	 * 491520 = (2048/16) * (1536/16) * 40
	 * 552960 = (2048/16) * (1536/16) * 45
	 * 592920 = (2592/16) * (1952/16) * 30
	 * 614400 = (2048/16) * (1536/16) * 50
	 * 779976 = (2592/16) * (1952/16) * 34 + (1280/16) * (720/16) * 30
	 * 790560 = (2592/16) * (1952/16) * 40
	 * 877500 = (1920/16) * (1088/16) * 90 + (848/16) * (480/16) * 90
	 * 889380 = (2592/16) * (1952/16) * 45
	 * 988200 = (2592/16) * (1952/16) * 50
	 * 972000 = (3840/16) * (2160/16) * 30
	 * 979200 = (1920/16) * (1088/16) * 120
	 * 1052340 = (1920/16) * (1088/16) * 124 + (720/16) * (480/16) * 30
	 * 1182900 = (1920/16) * (1088/16) * 140 + (720/16) * (480/16) * 30
	 * 1249200 = (3840/16) * (2160/16) * 31 + (1920/16) * (1088/16) * 30
	 * 1305600 = (1920/16) * (1088/16) * 160
	 * 1468800 = (1920/16) * (1088/16) * 180
	 * 1632000 = (1920/16) * (1088/16) * 200
	 * 1944000 = (3840/16) * (2160/16) * 60
	 * 1958400 = (1920/16) * (1088/16) * 240
	 * 2025000 = (3840/16) * (2160/16) * 60 + (720/16) * (480/16) * 60
	 * 2430000 = (3840/16) * (2160/16) * 75
	 * 2518200 = (3840/16) * (2160/16) * 60 + (2688/16) * (1520/16) * 30 + (848/16) * (480/16) * 60
	 * 2916000 = (3840/16) * (2160/16) * 90
	 * 3240000 = (3840/16) * (2160/16) * 100
	 * 2937600 = (1920/16) * (1088/16) * 360
	 * 3078000 = (3840/16) * (2160/16) * 95
	 * 3564000 = (3840/16) * (2160/16) * 110
	 * 3888000 = (3840/16) * (2160/16) * 120
	 * 4212000 = (3840/16) * (2160/16) * 130
	 * 4860000 = (3840/16) * (2160/16) * 150
	 * 5184000 = (3840/16) * (2160/16) * 160
	 * 5832000 = (3840/16) * (2160/16) * 180
	 * 7776000 = (3840/16) * (2160/16) * 240
	 */
	LOAD_3MP40 = (2048 * 1536 / 256 * 40),
	LOAD_3MP45 = (2048 * 1536 / 256 * 45),
	LOAD_5MP30 = (2592 * 1952 / 256 * 30),
	LOAD_3MP50 = (2048 * 1536 / 256 * 50),
	LOAD_5MP34_720P30 = (2592 * 1952 / 256 * 34 + 1280 * 720 / 256 * 30),
	LOAD_5MP40 = (2592 * 1952 / 256 * 40),
	LOAD_6MP30_480p90 = (1920 * 1088 / 256 * 90 + 848 * 480 / 256 * 90),
	LOAD_5MP45 = (2592 * 1952 / 256 * 45),
	LOAD_5MP50 = (2592 * 1952 / 256 * 50),
	LOAD_4KP30 = (3840 * 2160 / 256 * 30),
	LOAD_8MP30 = (1920 * 1088 / 256 * 120),
	LOAD_8MP31_480P30 = (1920 * 1088 / 256 * 124 + 720 * 480 / 256 * 30),
	LOAD_4KP31_1080P30 = (3840 * 2160 / 256 * 31 + 1920 * 1088 / 256 * 30),
	LOAD_8MP35_480P30 = (1920 * 1088 / 256 * 140 + 720 * 480 / 256 * 30),
	LOAD_8MP40 = (1920 * 1088 / 256 * 160),
	LOAD_8MP45 = (1920 * 1088 / 256 * 180),
	LOAD_8MP50 = (1920 * 1088 / 256 * 200),
	LOAD_4KP60 = (3840 * 2160 / 256 * 60),
	LOAD_8MP60 = (1920 * 1088 / 256 * 240),
	LOAD_4KP60_480P60 = (3840 * 2160 / 256 * 60 + 720 * 480 / 256 * 60),
	LOAD_4KP75 = (3840 * 2160 / 256 * 75),
	LOAD_4KP60_4MP30_480P60 = (3840 * 2160 / 256 * 60 + 2688 * 1520 / 256 *30 + 848 * 480 / 256 * 60),
	LOAD_4KP90  = (3840 * 2160 / 256 * 90),
	LOAD_4KP100  = (3840 * 2160 / 256 * 100),
	LOAD_1080P360 = (1920 * 1088 / 256 * 360),
	LOAD_4KP95  = (3840 * 2160 / 256 * 95),
	LOAD_4KP110 = (3840 * 2160 / 256 * 110),
	LOAD_4KP120 = (3840 * 2160 / 256 * 120),
	LOAD_4KP130 = (3840 * 2160 / 256 * 130),
	LOAD_4KP150 = (3840 * 2160 / 256 * 150),
	LOAD_4KP160 = (3840 * 2160 / 256 * 160),
	LOAD_4KP180 = (3840 * 2160 / 256 * 180),
	LOAD_4KP210 = (3840 * 2160 / 256 * 210),
	LOAD_4KP240 = (3840 * 2160 / 256 * 240),

	/* MJPEG maximum resolution */
	MAX_MJPEG_STM_RESO = ((32768 - 16) * (16384 - 16)) / 256,

	/*CV5 chip*/
	SYS_ENC_LOAD_CV5_66 = LOAD_4KP110,
	SYS_ENC_LOAD_CV5_66_MAX = LOAD_4KP130,
	SYS_ENC_LOAD_CV5_88 = LOAD_4KP160,
	SYS_ENC_LOAD_CV5_88_MAX = LOAD_4KP180,
	SYS_ENC_LOAD_CV5_99 = LOAD_4KP240,
	SYS_ENC_LOAD_CV5_99_MAX = LOAD_4KP240,

	MAX_STM_RESO_CV5_66 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,
	MAX_STM_RESO_CV5_88 = MAX_STM_RESO_CV5_66,
	MAX_STM_RESO_CV5_99 = MAX_STM_RESO_CV5_66,

	/*CV52 chip*/
	SYS_ENC_LOAD_CV52_33 = LOAD_4KP60,
	SYS_ENC_LOAD_CV52_33_MAX = LOAD_4KP60,
	SYS_ENC_LOAD_CV52_66 = LOAD_1080P360,
	SYS_ENC_LOAD_CV52_66_MAX = LOAD_4KP95,
	SYS_ENC_LOAD_CV52_99 = LOAD_4KP120,
	SYS_ENC_LOAD_CV52_99_MAX = LOAD_4KP120,

	MAX_STM_RESO_CV52_33 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,
	MAX_STM_RESO_CV52_66 = MAX_STM_RESO_CV52_33,
	MAX_STM_RESO_CV52_99 = MAX_STM_RESO_CV52_33,

	/*CV72 chip*/
	SYS_ENC_LOAD_CV72_33 = LOAD_8MP50,
	SYS_ENC_LOAD_CV72_33_MAX = LOAD_8MP50,
	SYS_ENC_LOAD_CV72_66 = LOAD_8MP30 * 3,
	SYS_ENC_LOAD_CV72_66_MAX = LOAD_8MP50 * 2,
	SYS_ENC_LOAD_CV72_66IQ = LOAD_8MP30 * 3,
	SYS_ENC_LOAD_CV72_66IQ_MAX = LOAD_8MP50 * 2,
	SYS_ENC_LOAD_CV72_88 = LOAD_8MP50 * 2,
	SYS_ENC_LOAD_CV72_88_MAX = LOAD_8MP50 + LOAD_8MP60,
	SYS_ENC_LOAD_CV72_88IQ = LOAD_8MP50 * 2,
	SYS_ENC_LOAD_CV72_88IQ_MAX = LOAD_8MP50 + LOAD_8MP60,
	SYS_ENC_LOAD_CV72_99 = LOAD_4KP120,
	SYS_ENC_LOAD_CV72_99_MAX = LOAD_4KP120,

	MAX_STM_RESO_CV72_33 = 8192 * 8192 / 256,
	MAX_STM_RESO_CV72_66 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72_66IQ = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72_88 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72_88IQ = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72_99 = MAX_STM_RESO_CV72_33,

	SYS_ENC_LOAD_CV72AX_36 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_36_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_56 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_56_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_76 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_76_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AX_86 = LOAD_8MP30 * 3,
	SYS_ENC_LOAD_CV72AX_86_MAX = LOAD_8MP30 * 3,
	SYS_ENC_LOAD_CV72AQ_56 = LOAD_8MP30,
	SYS_ENC_LOAD_CV72AQ_56_MAX = LOAD_8MP30,
	SYS_ENC_LOAD_CV72AQ_76 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AQ_76_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV72AQ_86 = LOAD_8MP30 * 3,
	SYS_ENC_LOAD_CV72AQ_86_MAX = LOAD_8MP30 * 3,

	MAX_STM_RESO_CV72AX_36 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AX_56 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AX_76 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AX_86 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AQ_56 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AQ_76 = MAX_STM_RESO_CV72_33,
	MAX_STM_RESO_CV72AQ_86 = MAX_STM_RESO_CV72_33,

	/*N1 chip*/
	SYS_ENC_LOAD_N1_99 = LOAD_4KP240,
	SYS_ENC_LOAD_N1_99_MAX = LOAD_4KP240,

	MAX_STM_RESO_N1_99 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,

	/*N1 655 chip*/
	SYS_ENC_LOAD_N1_655_99 = LOAD_4KP120,
	SYS_ENC_LOAD_N1_655_99_MAX = LOAD_4KP120,

	MAX_STM_RESO_N1_655_99 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,

	/*CV75 chip*/
	SYS_ENC_LOAD_CV75_33 = LOAD_3MP40,
	SYS_ENC_LOAD_CV75_33_MAX = LOAD_3MP50,
	SYS_ENC_LOAD_CV75_33EX = LOAD_5MP34_720P30,
	SYS_ENC_LOAD_CV75_33EX_MAX = LOAD_5MP34_720P30,
	SYS_ENC_LOAD_CV75_66 = LOAD_5MP40,
	SYS_ENC_LOAD_CV75_66_MAX = LOAD_5MP50,
	SYS_ENC_LOAD_CV75_68EX = LOAD_5MP40,
	SYS_ENC_LOAD_CV75_68EX_MAX = LOAD_5MP50,
	SYS_ENC_LOAD_CV75_88 = LOAD_8MP45,
	SYS_ENC_LOAD_CV75_88_MAX = LOAD_8MP50,
	SYS_ENC_LOAD_CV75_98 = LOAD_8MP60,
	SYS_ENC_LOAD_CV75_98_MAX = LOAD_8MP60,
	SYS_ENC_LOAD_CV75_99 = LOAD_8MP60,
	SYS_ENC_LOAD_CV75_99_MAX = LOAD_4KP120,
	SYS_ENC_LOAD_CV75_33M = LOAD_3MP40,
	SYS_ENC_LOAD_CV75_33M_MAX = LOAD_3MP45,
	SYS_ENC_LOAD_CV75_55M = LOAD_5MP40,
	SYS_ENC_LOAD_CV75_55M_MAX = LOAD_5MP45,
	SYS_ENC_LOAD_CV75_88M = LOAD_8MP31_480P30,
	SYS_ENC_LOAD_CV75_88M_MAX = LOAD_8MP35_480P30,
	SYS_ENC_LOAD_CV75_99M = LOAD_8MP31_480P30,
	SYS_ENC_LOAD_CV75_99M_MAX = LOAD_8MP35_480P30,

	MAX_STM_RESO_CV75_99 = 8192 * 8192 / 256,
	MAX_STM_RESO_CV75_98 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_88 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_68EX = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_66 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_33 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_33EX = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_33M = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_55M = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_88M = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75_99M = MAX_STM_RESO_CV75_99,

	SYS_ENC_LOAD_CV75A_56 = LOAD_8MP30,
	SYS_ENC_LOAD_CV75A_56_MAX = LOAD_8MP30,
	SYS_ENC_LOAD_CV75A_76 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV75A_76_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV75A_96 = LOAD_4KP60_4MP30_480P60,
	SYS_ENC_LOAD_CV75A_96_MAX = LOAD_4KP60_4MP30_480P60,
	SYS_ENC_LOAD_CV75A_56M = LOAD_6MP30_480p90,
	SYS_ENC_LOAD_CV75A_56M_MAX = LOAD_6MP30_480p90,

	SYS_ENC_LOAD_CV75AX_56 = LOAD_8MP30,
	SYS_ENC_LOAD_CV75AX_56_MAX = LOAD_8MP30,
	SYS_ENC_LOAD_CV75AX_76 = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV75AX_76_MAX = LOAD_8MP30 * 2,
	SYS_ENC_LOAD_CV75AX_56M = LOAD_6MP30_480p90,
	SYS_ENC_LOAD_CV75AX_56M_MAX = LOAD_6MP30_480p90,

	SYS_ENC_LOAD_CV75AQ_56 = LOAD_6MP30_480p90,
	SYS_ENC_LOAD_CV75AQ_56_MAX = LOAD_6MP30_480p90,
	SYS_ENC_LOAD_CV75AQ_76 = LOAD_8MP45,
	SYS_ENC_LOAD_CV75AQ_76_MAX = LOAD_8MP45,

	MAX_STM_RESO_CV75A_56 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75A_76 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75A_96 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75A_56M = MAX_STM_RESO_CV75_99,

	MAX_STM_RESO_CV75AX_56 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75AX_76 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75AQ_56 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75AQ_76 = MAX_STM_RESO_CV75_99,
	MAX_STM_RESO_CV75AX_56M = MAX_STM_RESO_CV75_99,

	/*CV7 chip*/
	SYS_ENC_LOAD_CV7_66 = LOAD_4KP120,
	SYS_ENC_LOAD_CV7_66_MAX = LOAD_4KP120,
	SYS_ENC_LOAD_CV7_66IQ = LOAD_4KP120,
	SYS_ENC_LOAD_CV7_66IQ_MAX = LOAD_4KP120,
	SYS_ENC_LOAD_CV7_88 = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_88_MAX = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_88IQ = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_88IQ_MAX = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_99 = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_99_MAX = LOAD_4KP240,
	SYS_ENC_LOAD_CV7_55M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7_55M_MAX = LOAD_4KP90,
	SYS_ENC_LOAD_CV7_66M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7_66M_MAX = LOAD_4KP90,
	SYS_ENC_LOAD_CV7_99M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7_99M_MAX = LOAD_4KP90,

	SYS_ENC_LOAD_CV7A_56 = LOAD_4KP150,
	SYS_ENC_LOAD_CV7A_56_MAX = LOAD_4KP150,
	SYS_ENC_LOAD_CV7A_76 = LOAD_4KP180,
	SYS_ENC_LOAD_CV7A_76_MAX = LOAD_4KP180,
	SYS_ENC_LOAD_CV7A_86 = LOAD_4KP210,
	SYS_ENC_LOAD_CV7A_86_MAX = LOAD_4KP210,
	SYS_ENC_LOAD_CV7A_56M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7A_56M_MAX = LOAD_4KP90,
	SYS_ENC_LOAD_CV7A_76M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7A_76M_MAX = LOAD_4KP90,

	SYS_ENC_LOAD_CV7AX_56 = LOAD_4KP150,
	SYS_ENC_LOAD_CV7AX_56_MAX = LOAD_4KP150,
	SYS_ENC_LOAD_CV7AX_76 = LOAD_4KP180,
	SYS_ENC_LOAD_CV7AX_76_MAX = LOAD_4KP180,
	SYS_ENC_LOAD_CV7AX_86 = LOAD_4KP210,
	SYS_ENC_LOAD_CV7AX_86_MAX = LOAD_4KP210,
	SYS_ENC_LOAD_CV7AX_56M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7AX_56M_MAX = LOAD_4KP90,
	SYS_ENC_LOAD_CV7AX_76M = LOAD_4KP90,
	SYS_ENC_LOAD_CV7AX_76M_MAX = LOAD_4KP90,

	MAX_STM_RESO_CV7_99 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,
	MAX_STM_RESO_CV7_66 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_66IQ = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_88 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_88IQ = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_99M = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_66M = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7_55M = MAX_STM_RESO_CV7_99,

	MAX_STM_RESO_CV7A_56 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7A_76 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7A_86 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7A_56M = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7A_76M = MAX_STM_RESO_CV7_99,

	MAX_STM_RESO_CV7AX_56 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7AX_76 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7AX_86 = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7AX_56M = MAX_STM_RESO_CV7_99,
	MAX_STM_RESO_CV7AX_76M = MAX_STM_RESO_CV7_99,

	/*CV8 chip*/
	SYS_ENC_LOAD_CV8_99 = LOAD_4KP240,
	SYS_ENC_LOAD_CV8_99_MAX = LOAD_4KP240,
	MAX_STM_RESO_CV8_99 = IAV_MAX_H26X_ENCODE_WIDTH * IAV_MAX_H26X_ENCODE_HEIGHT / 256,
} IAV_SYS_ENC_LOAD;

/*
 * Resolution limit items
 */
typedef enum {
	RESOLUTION_LIMIT_WARP = 0,
	RESOLUTION_LIMIT_PYRAMID = 1,
	RESOLUTION_LIMIT_RAW = 2,
	RESOLUTION_LIMIT_EFM = 3,
	RESOLUTION_LIMIT_IMG_SCALE = 4,
	RESOLUTION_LIMIT_NUM = 5,
	RESOLUTION_LIMIT_FIRST = RESOLUTION_LIMIT_WARP,
	RESOLUTION_LIMIT_LAST = RESOLUTION_LIMIT_NUM,
} IAV_RESOLUTION_LIMIT;

/*
 * Encode resource limitation
 */
typedef enum {
	MIN_WIDTH_IN_STREAM = 320,
	MIN_WIDTH_IN_STREAM_ROTATE = 240,
	MIN_WIDTH_IN_MJPEG_STREAM = 64,
	MIN_HEIGHT_IN_MJPEG_STREAM = 64,
	MIN_WIDTH_IN_ONE_TILE_HEVC = 256,
	MIN_HEIGHT_IN_STREAM = 160,
	MIN_WIDTH_DUAL_CORE_SPATIAL = 1280,
	MIN_WIDTH_IN_SINGLE_CORE_SPATIAL = 2048,

	MIN_PREV_WIDTH = 32,
	MIN_PREV_HEIGHT = 32,

	MAX_WIDTH_IN_BUFFER = 8 * 1024,
	MAX_HEIGHT_IN_BUFFER = 8 * 1024,

	MNBUF_LIMIT_MIN_INPUT_WIDTH = 128,
	MNBUF_LIMIT_MIN_INPUT_HEIGHT = 64,

	MIN_WARP_INPUT_WIDTH = 320,
	/* Fixme: A larger resolution will be supported. */
	MAX_WIDTH_FOR_TWO_REF = 2560,
	MAX_WIDTH_FOR_B_FRAME = 1920,

	/* full frame rate mode for CFA */
	MAX_HEIGHT_IN_FULL_FPS = 2048,
	MIN_WIDTH_IN_FULL_FPS = MIN_WIDTH_IN_STREAM_ROTATE,
	MIN_HEIGHT_IN_FULL_FPS = MIN_HEIGHT_IN_STREAM,

	/* high MP mode */
	MAX_WIDTH_IN_HIGH_MP = 8192,
	MAX_HEIGHT_IN_HIGH_MP = 8192,
} RESOLUTION_RESOURCE_LIMIT;

/*
 * DEBLOCKING filter limitation
 */
#define IAV_DEBLOCKING_ALPHA_MIN	(-6)
#define IAV_DEBLOCKING_ALPHA_MAX	(6)
#define IAV_DEBLOCKING_BETA_MIN		(-6)
#define IAV_DEBLOCKING_BETA_MAX		(6)

/*
 * Source buffer configuration
 */
typedef enum {
	MNBUF_MAX_ZOOMIN_FACTOR = 17,
	MNBUF_MAX_ZOOMOUT_FACTOR = 6,

	PCBUF_MAX_ZOOMIN_FACTOR = 1,
	PCBUF_MAX_ZOOMOUT_FACTOR = 16,

	PBBUF_MAX_ZOOMIN_FACTOR = 8,
	PBBUF_MAX_ZOOMOUT_FACTOR = 8,

	PABUF_MAX_ZOOMIN_FACTOR = 8,
	PABUF_MAX_ZOOMOUT_FACTOR = 16,

	PDBUF_MAX_ZOOMIN_FACTOR = 8,
	PDBUF_MAX_ZOOMOUT_FACTOR = 8,

	PEBUF_MAX_ZOOMIN_FACTOR = 1,
	PEBUF_MAX_ZOOMOUT_FACTOR = 8,

	PFBUF_MAX_ZOOMIN_FACTOR = 17,
	PFBUF_MAX_ZOOMOUT_FACTOR = 8,

	PYRAMID_MAX_ZOOMIN_FACTOR = 1,
	PYRAMID_MAX_ZOOMOUT_FACTOR = 8,

	STITCH_MAX_ZOOMOUT_FACTOR = 6,
	MNBUF_STITCH_MAX_ZOOMOUT_FACTOR = 4,
} SOURCE_BUFFER_ZOOM_FACTOR_LIMIT;

typedef enum {
	/*
	 * Resolution limitation for the 5 source buffers
	 */
#if defined(AMBA_SOC_CV75)
	MNBUF_LIMIT_MAX_WIDTH = 1216,
#else
	MNBUF_LIMIT_MAX_WIDTH = MAX_WIDTH_IN_HIGH_MP,
#endif
	MNBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
#if defined(AMBA_SOC_CV5) || defined(AMBA_SOC_CV52) || defined(AMBA_SOC_N1)
	PCBUF_LIMIT_MAX_WIDTH = 1408,
#else
	PCBUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
#endif
	PCBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
	PBBUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
	PBBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
	PABUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
	PABUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
	PDBUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
	PDBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
	PEBUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
	PEBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
	PFBUF_LIMIT_MAX_WIDTH = SRCBUF_LINE_BUFFER_WIDTH,
	PFBUF_LIMIT_MAX_HEIGHT = MAX_HEIGHT_IN_HIGH_MP,
} SOURCE_BUFFER_RESOLUTION_LIMIT;

/*
 * HDR configuration
 */
typedef enum {
	// Multi exposures supported in DSP
	MIN_HDR_EXPOSURES = 1,
	MAX_HDR_2X = 2,
	MAX_HDR_3X = 3,
	MAX_HDR_EXPOSURES = 4,
} IAV_HDR_PARAMS_LIMIT;

typedef enum {
	IAV_FRM_BUF_MIN_EMPTY_NUM = 2,
	IAV_FRM_BUF_MIN_BUF_NUM = 1,
	IAV_FRM_BUF_MAX_BUF_NUM = 10,
} IAV_FRM_BUF_PARAMS_LIMIT;

/*
 * EFM configuration
 */
typedef enum {
	IAV_EFM_MIN_BUF_NUM_H26X = 3,
	IAV_EFM_MIN_BUF_NUM_MJPEG = 2,
	IAV_EFM_MIN_BUF_NUM = IAV_EFM_MIN_BUF_NUM_MJPEG,
	IAV_EFM_MAX_BUF_NUM = 10,
	IAV_EFM_INIT_REQ_NUM = 4,
	IAV_EFM_DEFAULT_BUF_NUM = 4,
	IAV_EFM_EXT_ME_BUF_NUM = 4,
	IAV_EFM_ME_MAX_BUF_NUM = IAV_EFM_MAX_BUF_NUM + IAV_EFM_EXT_ME_BUF_NUM,

	/* max blur rect number for each EFM stream */
	IAV_EFM_RECT_NUM = 5,
} IAV_EFM_PARAMS_LIMIT;

typedef enum {
	RATIO_MULTI = 27,
	RATIO_DIV = 32,
} IAV_RAW_CMPR_PARAMS;

/*
 * External memory configuration
 */
typedef enum {
	IAV_EXT_MEM_CANVAS = 0,
	IAV_EXT_MEM_PYRAMID = 1,
	IAV_EXT_MEM_EFM_YUV = 2,
	IAV_EXT_MEM_EFM_ME = 3,
	IAV_EXT_MEM_NUM = 4,
} IAV_EXT_MEM_CFG;

/*
 * Private mask type configuration
 */
typedef enum {
	IAV_PM_TYPE_PIXEL = 0,
	IAV_PM_TYPE_SCALED = 1,
	IAV_PM_TYPE_NUM = 2,
} IAV_PM_TYPE;

/*
 * Overlay memory configuration
 */
typedef enum {
	/* Overlay width for CV5x platforms shares the same line buffer width limit,
	 * and it cannot do stitching.
	 */
#if defined(AMBA_SOC_CV75)
	OVERLAY_AREA_MAX_WIDTH = 1216,
#else
	OVERLAY_AREA_MAX_WIDTH = 2048,
#endif
	MAX_OVERLAY_SPLIT_AREA_NUM = 32,
	/* Max overlay and YUV remap number for all streams before splitting. */
	MAX_OVERLAY_YUV_REMAP_AREA_NUM_TOTAL = 64,
	OVERLAY_CONTENT_SIZE = IAV_MEM_OVERLAY_SIZE,
	CANVAS_OVERLAY_CONTENT_SIZE = IAV_MEM_CANVAS_OVERLAY_SIZE,
	OVERLAY_CLUT_SIZE = 1024,

	OVERLAY_TOGGLE_NUM = 8,

	/* There are 32 overlay cmds in total, each has sizeof(osd_insert_buf_t) Bytes. */
	OVERLAY_CMD_NUM = 32,
	OVERLAY_CFG_SIZE = sizeof(osd_insert_buf_t),
	OVERLAY_CMD_PART_SIZE = (OVERLAY_CFG_SIZE * OVERLAY_CMD_NUM),
	OVERLAY_CMD_SIZE = (OVERLAY_CMD_PART_SIZE * OVERLAY_TOGGLE_NUM *
		IAV_MAX_ENCODE_STREAMS_NUM),
	CANVAS_OVERLAY_CMD_SIZE = (OVERLAY_CMD_PART_SIZE * OVERLAY_TOGGLE_NUM *
		IAV_MAX_CANVAS_BUF_NUM),

	OVERLAY_RSV_SIZE = OVERLAY_CMD_SIZE,
	CANVAS_OVERLAY_RSV_SIZE = CANVAS_OVERLAY_CMD_SIZE,
} IAV_OVERLAY_PARAMS;

/*
 * Fusion Blend CLUT Memory Configuration
 */
typedef enum {
	SINGLE_FUSION_CLUT_BUFFER_SIZE = OVERLAY_CLUT_SIZE,
	FUSION_CLUT_BUFFER_SIZE = SINGLE_FUSION_CLUT_BUFFER_SIZE * IAV_MAX_CHANNEL_NUM,
} IAV_FUSION_PARAMS;

/*
 * YUV remap memory configuration
 */
typedef enum {
	YUV_REMAP_CONTENT_SIZE = IAV_MEM_YUV_REMAP_SIZE,
	YUV_REMAP_CLUT_SIZE = 1024,

	YUV_REMAP_TOGGLE_NUM = 8,

	/* There are 32 yuv remap cmds in total, each has 20 Bytes.
	 * We may need to  Adjust this if DSP structure changes */
	YUV_REMAP_CMD_SIZE = sizeof(osd_insert_buf_t),
	YUV_REMAP_CMD_NUM = 32,
	YUV_REMAP_CMD_PART_SIZE = (YUV_REMAP_CMD_SIZE * YUV_REMAP_CMD_NUM),
	YUV_REMAP_CMD_BUF_SIZE = (YUV_REMAP_CMD_PART_SIZE * YUV_REMAP_TOGGLE_NUM *
		IAV_MAX_ENCODE_STREAMS_NUM),

	YUV_REMAP_RSV_SIZE = YUV_REMAP_CMD_BUF_SIZE,

	YUV_REMAP_AREA_MAX_WIDTH = OVERLAY_AREA_MAX_WIDTH,
} IAV_YUV_REMAP_PARAMS;

/*
 * Postp scale memory configuration
 */
#define GET_ME1_OFFSET(n)   ROUND_UP(((n) >> 2), 2)
#define GET_ME0_OFFSET(n)   ROUND_UP(((n) >> 3), 2)
#define ME1_DIV  			(4)
#define ME0_DIV  			(8)
#define ME_WIDTH_ALIGN		(4)
#define ME_HEIGHT_ALIGN		(2)
#define GET_ME1_WIDTH(n)	ROUND_UP(DIV_ROUND((n), ME1_DIV), ME_WIDTH_ALIGN)
#define GET_ME1_HEIGHT(n)	ROUND_UP(DIV_ROUND((n), ME1_DIV), ME_HEIGHT_ALIGN)
#define GET_ME0_WIDTH(n)	ROUND_UP(DIV_ROUND((n), ME0_DIV), ME_WIDTH_ALIGN)
#define GET_ME0_HEIGHT(n)	ROUND_UP(DIV_ROUND((n), ME0_DIV), ME_HEIGHT_ALIGN)

typedef enum {
	IAV_DEF_POSTP_SCALE_Q_DEPTH = 7,

	POSTP_SCALE_CMD_SIZE = sizeof(iproc_scale_job_t), // 64 bytes
	POSTP_SCALE_CMD_TYPE_NUM = 3, // yuv + me0 + me1
	POSTP_SCALE_TOGGLE_NUM = 8,
	POSTP_SCALE_CMD_PART_SIZE = (POSTP_SCALE_CMD_SIZE * IAV_MAX_POSTP_SCALE_AREA_NUM * POSTP_SCALE_CMD_TYPE_NUM),
	POSTP_SCALE_CMD_SINGLE_CANVAS_SIZE = (POSTP_SCALE_CMD_PART_SIZE * POSTP_SCALE_TOGGLE_NUM),
	POSTP_SCALE_CMD_TOTAL_BUF_SIZE = (POSTP_SCALE_CMD_SINGLE_CANVAS_SIZE *
		IAV_MAX_CANVAS_BUF_NUM),

	USER_POSTP_SCALE_ALPHA_NUM = 1,
	IAV_POSTP_SCALE_ALPHA_TOGGLE_NUM = 2,
} IAV_POSTP_SCALE_PARAMS;

/*
 * Blur memory configuration
 */
typedef enum {
	BLUR_CONTENT_SIZE = IAV_MEM_BLUR_SIZE,
	BLUR_TOGGLE_NUM = 8,

	/* There are 64 blur cmds in total, each has sizeof(blur_buf_t) Bytes. */
	BLUR_CMD_SIZE = sizeof(blur_buf_t),
	BLUR_CMD_NUM = 64,
	BLUR_CMD_PART_SIZE = (BLUR_CMD_SIZE * BLUR_CMD_NUM),
	BLUR_CMD_BUF_SIZE = (BLUR_CMD_PART_SIZE * BLUR_TOGGLE_NUM *
		IAV_MAX_ENCODE_STREAMS_NUM),

#if defined(AMBA_SOC_CV5) || defined(AMBA_SOC_CV52)
	BLUR_COLORED_UV_SIZE = 128,
#else
	BLUR_COLORED_UV_SIZE = 256,
#endif
	BLUR_COLORED_UV_TOTAL_SIZE = (MAX_NUM_BLUR_COLOR * BLUR_COLORED_UV_SIZE),
	BLUR_RSV_SIZE = BLUR_CMD_BUF_SIZE + BLUR_COLORED_UV_TOTAL_SIZE,

	/**
	 * Blur MEMORY Layout:
	 *
	 *	 +-------------------------+
	 *	 | 1. Blur content mem     |
	 *	 +-------------------------+
	 *	 | 2. Blur color table mem |
	 *	 +-------------------------+
	 *	 | 3. Blur buf cfg mem     |
	 *	 |    strm0_0 | strm0_1 | strm0_(BLUR_TOGGLE_NUM - 1) |
	 *	 |    strm1_0 | strm1_1 | strm1_(BLUR_TOGGLE_NUM - 1) |
	 *	 |    strm(StrmNUM - 1)_0 | strm(StrmNUM - 1)_1 | strm(StrmNUM - 1)_(BLUR_TOGGLE_NUM - 1) |
	 *	 +-------------------------+
	 *
	 */

	BLUR_AREA_MAX_WIDTH = 2048,
	BLUR_AREA_NUM_DEFAULT = 8,
	BLUR_AREA_NUM_MAX_TOTAL = 80, /*!< Max blur area number for all streams before splitting. */
} IAV_BLUR_PARAMS;

/*
 * Smooth Blur memory configuration
 */
typedef enum {
	SMOOTH_BLUR_CONTENT_SIZE = IAV_MEM_SMOOTH_BLUR_SIZE,
	SMOOTH_BLUR_TOGGLE_NUM = 8,

	/* There are 32 smooth_blur cmds in total, each has sizeof(blur_buf_t) Bytes. */
	SMOOTH_BLUR_CMD_SIZE = sizeof(blur_buf_t),
	SMOOTH_BLUR_CMD_NUM = BLUR_CMD_NUM,
	SMOOTH_BLUR_CMD_PART_SIZE = (SMOOTH_BLUR_CMD_SIZE * SMOOTH_BLUR_CMD_NUM),
	SMOOTH_BLUR_CMD_BUF_SIZE = (SMOOTH_BLUR_CMD_PART_SIZE * SMOOTH_BLUR_TOGGLE_NUM *
		IAV_MAX_ENCODE_STREAMS_NUM),

	SMOOTH_BLUR_RSV_SIZE = SMOOTH_BLUR_CMD_BUF_SIZE,

	/**
	 * Smooth Blur MEMORY Layout:
	 *
	 *	 +--------------------------------+
	 *	 | 1. Smooth Blur content mem     |
	 *	 +--------------------------------+
	 *	 | 2. Smooth Blur buf cfg mem     |
	 *	 |    strm0_0 | strm0_1 | strm0_(SMOOTH_BLUR_TOGGLE_NUM - 1) |
	 *	 |    strm1_0 | strm1_1 | strm1_(SMOOTH_BLUR_TOGGLE_NUM - 1) |
	 *	 |    strm(StrmNUM - 1)_0 | strm(StrmNUM - 1)_1 | strm(StrmNUM - 1)_(SMOOTH_BLUR_TOGGLE_NUM - 1) |
	 *	 +--------------------------------+
	 *
	 */

	SMOOTH_BLUR_AREA_MAX_WIDTH = BLUR_AREA_MAX_WIDTH,
	SMOOTH_BLUR_AREA_NUM_DEFAULT = BLUR_AREA_NUM_DEFAULT,
	SMOOTH_BLUR_AREA_NUM_MAX_TOTAL = BLUR_AREA_NUM_MAX_TOTAL, /*!< Max smooth_blur area number
		for all streams before splitting. */
} IAV_SMOOTH_BLUR_PARAMS;

/*
 * Multi channel memory configuration
 */
typedef enum {
	SUB_DSP_CMD_SIZE = DSP_CMD_SIZE,
	MAX_CANVAS_NUM = 20,
	CMD_NUM_PER_PART = 128,
	VIN_CMD_NUM_PER_PART = 6,
	MAX_VIN_FOV_NUM = 4,
	MAX_VIN_NUM = AMBA_MAX_REAL_VIN_NUM,

	CANVAS_INFO_NUM = (128),
	PYRAMID_INFO_NUM = (64),
	IDSP_DEBUG_INFO_NUM = (128),
	POSTP_INFO_NUM = (64),
	MO_INFO_NUM = (8),
	DECI_INFO_NUM = (8),
	CANVAS_INFO_FIFO_UNIT_SIZE = ALIGN(sizeof(srcbuf_info_t), IAV_DSP_BUF_PITCH_ALIGN),
	PYRAMID_INFO_FIFO_UNIT_SIZE = ALIGN(sizeof(hier_pic_info_t), IAV_DSP_BUF_PITCH_ALIGN),
	IDSP_DEBUG_INFO_FIFO_UNIT_SIZE = ALIGN(sizeof(iproc_debug_info_t), IAV_DSP_BUF_PITCH_ALIGN),
	POSTP_MSG_FIFO_UNIT_SIZE = ALIGN(sizeof(postp_info_t), POSTP_INFO_FIFO_UNIT_SIZE),
	MO_MSG_FIFO_UNIT_SIZE = ALIGN(sizeof(mo_info_t), MO_INFO_FIFO_UNIT_SIZE),
	DECI_INFO_FIFO_UNIT_SIZE = ALIGN(sizeof(iproc_pass1a_deci_info_t), IAV_DSP_BUF_PITCH_ALIGN),

	MULTI_CHAN_TOTAL_SIZE = 0,
} IAV_MULTI_CHAN_PARAMS;

/*
 * Stream cmd list memory configuration
 */
typedef enum{
	PROC_ENC_CMD_LIST_NUM_PER_PART = (32),
	PROC_ENC_CMD_LIST_PART_SIZE = (SUB_DSP_CMD_SIZE * PROC_ENC_CMD_LIST_NUM_PER_PART),
	PROC_ENC_CMD_LIST_ALL_SIZE = (PROC_ENC_CMD_LIST_PART_SIZE * IAV_MAX_ENCODE_STREAMS_NUM),

	PROC_ENC_CMD_LIST_OFFSET = 0,

	ENC_LIST_TOTAL_SIZE = PROC_ENC_CMD_LIST_ALL_SIZE,

	ENC_SETUP_CMD = (1 << 0),
	ENC_START_CMD = (1 << 1),
	ENC_STOP_CMD = (1 << 2),
	ENC_OVERLAY_INSERT_CMD = (1 << 3),
	ENC_BLUR_INSERT_CMD = (1 << 4),
	ENC_REALTIME_ENCODE_SETUP = (1 << 5),
	ENC_YUV_REMAP_INSERT_CMD = (1 << 6),
} IAV_STREAM_PARAMS;

/*
 * Canvas cmd list memory configuration
 */
typedef enum{
	PROC_CANVAS_CMD_LIST_NUM_PER_PART = (32),
	PROC_CANVAS_CMD_LIST_PART_SIZE = (SUB_DSP_CMD_SIZE * PROC_CANVAS_CMD_LIST_NUM_PER_PART),
	PROC_CANVAS_CMD_LIST_ALL_SIZE = (PROC_CANVAS_CMD_LIST_PART_SIZE * IAV_MAX_CANVAS_BUF_NUM),

	PROC_CANVAS_CMD_LIST_OFFSET = 0,

	CANVAS_LIST_TOTAL_SIZE = PROC_CANVAS_CMD_LIST_ALL_SIZE,

	CANVAS_BLUR_INSERT_CMD = (1 << 0),
	CANVAS_OVERLAY_INSERT_CMD = (1 << 1),
	CANVAS_POSTP_SCALE_INSERT_CMD = (1 << 2),
} IAV_CANVAS_PARAMS;

/*
 * Sync command memory configuration
 * layout:  |---frame/idsp sync---|
 *          |       cmd pool      |
 *          |---------------------|
 */
typedef enum {
	CMD_SYNC_CMD_SIZE = (DSP_CMD_SIZE),
	CMD_SYNC_CMD_POOL_TOGGLED_NUM = (8 * IAV_MAX_ENCODE_STREAMS_NUM),
	CMD_SYNC_CMD_POOL_SIZE = (CMD_SYNC_CMD_POOL_TOGGLED_NUM * CMD_SYNC_CMD_SIZE),
	CMD_SYNC_TOTAL_SIZE = (CMD_SYNC_CMD_POOL_SIZE),
} IAV_CMD_SYNC_PARAMS;

/*
 * Stream Sync command memory configuration
 */
typedef enum {
	CMD_STREAM_SYNC_CMD_SIZE = (DSP_CMD_SIZE),
	CMD_STREAM_SYNC_TOGGLED_NUM = (8),
	CMD_STREAM_SYNC_SIZE = (CMD_STREAM_SYNC_CMD_SIZE * CMD_STREAM_SYNC_TOGGLED_NUM),
	CMD_STREAM_SYNC_TOTAL_SIZE = (CMD_STREAM_SYNC_SIZE * IAV_MAX_ENCODE_STREAMS_NUM),
} IAV_CMD_STREAM_SYNC_PARAMS;

/*
 * QP ROI matrix memory configuration
 */
typedef enum {
	/* 128K is the size of qp matrix for 4Kx2K */
	SINGLE_QP_MATRIX_SIZE = IAV_MEM_ROI_MATRIX_SIZE,
	STREAM_QP_MATRIX_NUM = IAV_ROI_NUM_FOR_IPB_FRAMES,
	STREAM_QP_MATRIX_SIZE = (SINGLE_QP_MATRIX_SIZE * STREAM_QP_MATRIX_NUM),
	QP_MATRIX_SIZE = (STREAM_QP_MATRIX_SIZE * IAV_MAX_ENCODE_STREAMS_NUM),
	UQP_NUM = (1),
	QP_MATRIX_TOGGLED_NUM = (4),
	QP_MATRIX_TOGGLED_NUM_MAX = (16),
	/* 128KB * 8 * (1 + 4) = 5120 KB for 1 qp matrix */
	/* 128KB * 3 * 8 * (1 + 4) = 15360 KB for 3 qp matrixes */
	QP_MATRIX_TOTAL_SIZE = (QP_MATRIX_SIZE * (UQP_NUM + QP_MATRIX_TOGGLED_NUM)),
} IAV_QPMATRIX_PARAMS;

/*
 * Privacy Mask Memory Configuration
 */
typedef enum {
	/* User Privacy Mask Partition */
	UPMP_NUM = 1,
	IAV_MASK_TOGGLE_NUM = 4,

	/* Privacy mask memory configuration */
	MASK_WIDTH_MAX = MAX_WIDTH_IN_HIGH_MP,
	MASK_HEIGHT_MAX = MAX_HEIGHT_IN_HIGH_MP,

	/* User Privacy Mask Partition */
	MASK_PARTITION_SIZE = PAGE_ALIGN(ALIGN(MASK_WIDTH_MAX / 8, IAV_DSP_BUF_PITCH_ALIGN) * MASK_HEIGHT_MAX),
	MASK_TOTAL_SIZE = (MASK_PARTITION_SIZE * (IAV_MASK_TOGGLE_NUM + UPMP_NUM) * CONFIG_AMBARELLA_MAX_CHANNEL_NUM),

	/**
	 * MASK MEMORY Layout:
	 *
	 *	 +--------------------+
	 *	 | User_0 | User_1 | User_(ChanNum - 1) |
	 *	 +--------------------+
	 *	 | DSP0.0 | DSP0.1 | DSP0.2 | DSP0.(IAV_MASK_TOGGLE_NUM - 1) |
	 *	 +--------------------+
	 *	 | DSP1.0 | DSP1.1 | DSP1.2 | DSP1.(IAV_MASK_TOGGLE_NUM - 1) |
	 *	 +--------------------+
	 *	 | DSP(ChanNum - 1).0 | DSP(ChanNum - 1).1 | DSP(ChanNum - 1).2 | DSP(ChanNum - 1).(IAV_MASK_TOGGLE_NUM - 1) |
	 *	 +--------------------+
	 *
	 */

	// Minimum PM size for dsp setup and scale PM buffer size
	MIN_PM_WIDTH = 512,
	MIN_PM_PITCH = 64,
	MIN_PM_HEIGHT = 16,
} IAV_MASK_PARAMS;

/*
 * Custom SEI Memory Configuration
 */
typedef enum {
	/* Default 128 bytes is the single size of custom sei buffer */
	SINGLE_CUSTOM_SEI_DEFAULT_SIZE = 128,
	SINGLE_CUSTOM_SEI_MAX_SIZE = 8192,
	/* Min sei payload size must larger than 16 */
	SINGLE_CUSTOM_SEI_MIN_SIZE = 16,
	STREAM_CUSTOM_SEI_MAX_NUM = 10,
	STREAM_CUSTOM_SEI_MIN_NUM = 4,
	USEI_NUM = 1,
	STREAM_CUSTOM_SEI_SIZE = (SINGLE_CUSTOM_SEI_DEFAULT_SIZE * (STREAM_CUSTOM_SEI_MAX_NUM + USEI_NUM)),
	CUSTOM_SEI_BUFFER_SIZE = (STREAM_CUSTOM_SEI_SIZE * IAV_MAX_ENCODE_STREAMS_NUM),
} IAV_CUSTOM_SEI_PARAMS;

typedef enum {
	JPEG_QT_SIZE = 128,
	JPEG_QT_BUFFER_NUM = 4,
	JPEG_QT_TOTAL_SIZE = (IAV_MAX_ENCODE_STREAMS_NUM * JPEG_QT_SIZE * JPEG_QT_BUFFER_NUM),
} IAV_JPEG_QT_PARAMS;

/*
 * Picture Statistics Memory Configuration
 * */
#define PIC_STATISTICS_SHIFT (13)
typedef enum {
	SINGLE_PIC_STAT_SIZE = (1U << PIC_STATISTICS_SHIFT),
	PIC_STAT_NUM = IAV_MAX_STATIS_NUM,
	PIC_STAT_STREAM_NUM = CONFIG_PIC_STATISTICS_DUMP_STREAM_NUM,
	STREAM_PIC_STAT_SIZE = (SINGLE_PIC_STAT_SIZE * PIC_STAT_NUM),
	PIC_STAT_SIZE = (STREAM_PIC_STAT_SIZE * PIC_STAT_STREAM_NUM),

	MV_STAT_NUM = IAV_MAX_STATIS_NUM,
	MV_STAT_STREAM_NUM = IAV_MV_STREAM_NUM,
	STREAM_MV_STAT_SIZE = IAV_MEM_MV_SIZE,
	MV_STAT_SIZE = (STREAM_MV_STAT_SIZE * MV_STAT_STREAM_NUM),
} IAV_STAT_PARAMS;

/*
 * WARP Configuration
 */

/* Warp Memory Layout
|----------ch0----------|--------- ch1 ----------|
| WARP_VECT_PART_SIZE	| WARP_VECT_PART_SIZE	|
| area 0 : H				| area 0 : H				|
|             V				|             V				|
| area 1 : H				| area 1 : H				|
|             V				|             V				|
|	...					|	...					|
| area11: H				| area11: H				|
|             V				|             V				|
*/
typedef enum {
	VWARP_BLOCK_HEIGHT_MIN = 28,
	VWARP_BLOCK_HEIGHT_MAX = 64,
	VWARP_BLOCK_HEIGHT_DEFAULT = 32,
	MAX_WARP_PADDING_WIDTH = 512,
	MIN_REGION_WIDTH_IN_WARP = 352,
	WARP_INPUT_WIDTH_DEFAULT = 2048,

	IAV_WARP_TOGGLE_NUM = 6,

	WARP_VECTOR_NUM = 3,		/* Three tables for each area, H table, V table, ME1-V table. */
	WARP_TABLE_AREA_MAX_WIDTH = 128,
	WARP_TABLE_AREA_MAX_WIDTH_LDC = WARP_TABLE_AREA_MAX_WIDTH,
	WARP_TABLE_AREA_MAX_HEIGHT = 96,
	WARP_TABLE_AREA_MAX_SIZE = WARP_TABLE_AREA_MAX_HEIGHT *
		WARP_TABLE_AREA_MAX_WIDTH,
	WARP_TABLE_AREA_MAX_SIZE_LDC = (WARP_TABLE_AREA_MAX_WIDTH_LDC
	    * WARP_TABLE_AREA_MAX_HEIGHT),
	/* User Warp Partition */
	UWARP_NUM = 1,
	WARP_VECT_PART_SIZE = (MAX_NUM_WARP_AREAS * \
		WARP_TABLE_AREA_MAX_SIZE * sizeof(s16) * WARP_VECTOR_NUM),
	WARP_VECT_TOTAL_SIZE = CONFIG_AMBARELLA_MAX_CHANNEL_NUM * WARP_VECT_PART_SIZE *
		(IAV_WARP_TOGGLE_NUM + UWARP_NUM),

	WARP_BUFFER_TOTAL_SIZE = WARP_VECT_TOTAL_SIZE,

	HWARP_PADDING_TABLE_MEM_SIZE = HWARP_PADDING_TABLE_PITCH_IN_BYTES * (IAV_WARP_TOGGLE_NUM + UWARP_NUM) * MAX_NUM_WARP_AREAS,

	MAX_WARP_VH_H_DOWNSCALE_FACTOR = 16,/* Inclusive. */
	MAX_WARP_VH_H_UPSCALE_FACTOR = 4,	/* Inclusive. */
	MAX_WARP_VH_V_DOWNSCALE_FACTOR = 8,	/* Exclusive. */
	MAX_WARP_VH_V_UPSCALE_FACTOR = 4,	/* Inclusive. */
	MAX_WARP_HV_H_DOWNSCALE_FACTOR = 16,	/* Inclusive. */
	MAX_WARP_HV_H_UPSCALE_FACTOR = 4,	/* Inclusive. */
	MAX_WARP_HV_V_DOWNSCALE_FACTOR = 8,	/* Inclusive. */
	MAX_WARP_HV_V_UPSCALE_FACTOR = 4,	/* Inclusive. */
} IAV_WARP_PARAMS;

/*
 * CE GO Map Memory Configuration
 * */
typedef enum {
	CE_GO_MAP_PER_PIXEL_SIZE = 4,
	SINGLE_CE_GO_MAP_DEFAULT_SIZE = 128,
	CE_GO_MAP_BUFFER_NUM = 8,
	CE_GO_MAP_BUFFER_TOTAL_SIZE = CONFIG_AMBARELLA_MAX_CHANNEL_NUM * SINGLE_CE_GO_MAP_DEFAULT_SIZE * \
		CE_GO_MAP_BUFFER_NUM,
} IAV_CE_GO_MAP_PARAMS;


typedef enum {
	TML_FUSION_CLUT_SIZE = (256 * 4),

	USER_TML_FUSION_NUM = 1,
	IAV_TML_FUSION_TOGGLE_NUM = 4,
	TML_FUSION_CLUT_TOTAL_SIZE_PER_CHAN = TML_FUSION_CLUT_SIZE * (IAV_TML_FUSION_TOGGLE_NUM + USER_TML_FUSION_NUM),
	TML_FUSION_CLUT_TOTAL_SIZE = (TML_FUSION_CLUT_TOTAL_SIZE_PER_CHAN * CONFIG_AMBARELLA_MAX_CHANNEL_NUM),

	/**
	 * TML Fusion Memory Layout:
	 *   CLUT:
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      User_0        |     User_1         |     User_2         |     User_(ChanNUM - 1)                                |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      DSP0.0        |     DSP0.1         |     DSP0.2         |     DSP0.(IAV_TML_FUSION_TOGGLE_NUM - 1)         |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      DSP1.0        |     DSP1.1         |     DSP1.2         |     DSP1.(IAV_TML_FUSION_TOGGLE_NUM - 1)         |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 | DSP(ChanNUM - 1).0 | DSP(ChanNUM - 1).1 | DSP(ChanNUM - 1).2 | DSP(ChanNUM - 1).(IAV_TML_FUSION_TOGGLE_NUM - 1) |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *
	 *   Chroma blend alpha table :
 	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      User_0        |     User_1         |     User_2         |     User_(ChanNUM - 1)                                |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      DSP0.0        |     DSP0.1         |     DSP0.2         |     DSP0.(IAV_TML_FUSION_TOGGLE_NUM - 1)         |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 |      DSP1.0        |     DSP1.1         |     DSP1.2         |     DSP1.(IAV_TML_FUSION_TOGGLE_NUM - 1)         |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 *	 | DSP(ChanNUM - 1).0 | DSP(ChanNUM - 1).1 | DSP(ChanNUM - 1).2 | DSP(ChanNUM - 1).(IAV_TML_FUSION_TOGGLE_NUM - 1) |
	 *	 +----------------------------------------------------------------------------------------------------------------------+
	 */

	/* User chroma blend alpha table default value */
	TML_FUSION_ALPHA_INVALID = 0,
	TML_FUSION_ALPHA_WIDTH_DEF = 128,
	TML_FUSION_ALPHA_HEIGHT_DEF = 128,
} IAV_TML_FUSION_PARAMS;

/*
 * OF NN Memory Configuration
 * */
typedef enum {
	OF_NN_BUF_NUM_DEF = 31,
	OF_NN_DELAY_COUNT_MAX = 3,
	SW_SCORE_DEFAULT_SIZE = (512 * 1024),      /* 512KB for SW score */
	WARP_TABLE_DEFAULT_SIZE = (512 * 1024),    /* 512KB for warp table */
	OF_NN_BUFFER_TOTAL_SIZE = SW_SCORE_DEFAULT_SIZE + WARP_TABLE_DEFAULT_SIZE,
} IAV_OF_NN_PARAMS;

#define OF_NN_RSV_SIZE		(64 * 1024)	/* 64KB reserved space for OF NN */

/*
 * Memory configuration
 */
typedef enum {
	IAV_DRAM_SIZE_1Gb = 0x1,
	IAV_DRAM_SIZE_2Gb = 0x2,
	IAV_DRAM_SIZE_4Gb = 0x4,
	IAV_DRAM_SIZE_8Gb = 0x8,
	IAV_DRAM_SIZE_16Gb = 0x10,
	IAV_DRAM_SIZE_32Gb = 0x20,
	IAV_DRAM_SIZE_64Gb = 0x40,
	IAV_DRAM_SIZE_128Gb = 0x80,

#if (IAV_MEM_BLUR_SIZE > 0)
	IAV_DRAM_BLUR = PAGE_ALIGN(BLUR_CONTENT_SIZE + BLUR_RSV_SIZE),
#else
	IAV_DRAM_BLUR = 0,
#endif

#if (IAV_MEM_SMOOTH_BLUR_SIZE > 0)
	IAV_DRAM_SMOOTH_BLUR = PAGE_ALIGN(SMOOTH_BLUR_CONTENT_SIZE + SMOOTH_BLUR_RSV_SIZE),
#else
	IAV_DRAM_SMOOTH_BLUR = 0,
#endif

#if (IAV_MEM_ARB_BLUR_SIZE > 0)
	IAV_DRAM_ARB_BLUR = PAGE_ALIGN(IAV_MEM_ARB_BLUR_SIZE),
#else
	IAV_DRAM_ARB_BLUR = 0,
#endif

#if (IAV_MEM_ARB_SMOOTH_BLUR_SIZE > 0)
	IAV_DRAM_ARB_SMOOTH_BLUR = PAGE_ALIGN(IAV_MEM_ARB_SMOOTH_BLUR_SIZE),
#else
	IAV_DRAM_ARB_SMOOTH_BLUR = 0,
#endif

#ifdef CONFIG_AMBARELLA_IAV_H26X_SCALELIST
	IAV_DRAM_H26X_SCALELIST = PAGE_ALIGN(H26X_SCALELIST_BUFFER_SIZE),
#else
	IAV_DRAM_H26X_SCALELIST = 0,
#endif

#if (IAV_MEM_YUV_REMAP_SIZE > 0)
	IAV_DRAM_YUV_REMAP = PAGE_ALIGN(YUV_REMAP_CONTENT_SIZE + YUV_REMAP_RSV_SIZE),
#else
	IAV_DRAM_YUV_REMAP = 0,
#endif

#if (IAV_MEM_CANVAS_OVERLAY_SIZE > 0)
	IAV_DRAM_CANVAS_OVERLAY = PAGE_ALIGN(CANVAS_OVERLAY_CONTENT_SIZE + CANVAS_OVERLAY_RSV_SIZE),
#else
	IAV_DRAM_CANVAS_OVERLAY = 0,
#endif

#if (IAV_MEM_ARB_BLEND_ALPHA_SIZE > 0)
	IAV_DRAM_ARB_BLEND_ALPHA = PAGE_ALIGN(IAV_MEM_ARB_BLEND_ALPHA_SIZE),
#else
	IAV_DRAM_ARB_BLEND_ALPHA = 0,
#endif

#if (IAV_MEM_OF_NN_SIZE > 0)
	IAV_DRAM_OF_NN = PAGE_ALIGN(IAV_MEM_OF_NN_SIZE),
#else
	IAV_DRAM_OF_NN = 0,
#endif

#if (IAV_MEM_TML_FUSION_SIZE > 0)
	IAV_DRAM_TML_FUSION = PAGE_ALIGN(IAV_MEM_TML_FUSION_SIZE),
#else
	IAV_DRAM_TML_FUSION = 0,
#endif

	IAV_DRAM_MULTI_COLOR_MASK = 0,
	IAV_DRAM_DEC_BSB = 0,

	IAV_DRAM_INT_BSB = DSP_INT_BSB_SIZE,
	IAV_DRAM_BSB = DSP_BSB_SIZE,
	IAV_DRAM_USR = PAGE_ALIGN(IAV_MEM_USR_SIZE),
	IAV_DRAM_MV = PAGE_ALIGN(MV_STAT_SIZE),
	IAV_DRAM_STAT = PAGE_ALIGN(PIC_STAT_SIZE),
	IAV_DRAM_OVERLAY = PAGE_ALIGN(OVERLAY_CONTENT_SIZE + OVERLAY_RSV_SIZE),
	IAV_DRAM_QPM = PAGE_ALIGN(QP_MATRIX_TOTAL_SIZE),
	IAV_DRAM_WARP = PAGE_ALIGN(WARP_BUFFER_TOTAL_SIZE),
	IAV_DRAM_QUANT = PAGE_ALIGN(JPEG_QT_TOTAL_SIZE),
	IAV_DRAM_IMG = PAGE_ALIGN(TOTAL_IMG_SIZE),
	IAV_DRAM_CE_GO_MAP = PAGE_ALIGN(CE_GO_MAP_BUFFER_TOTAL_SIZE),

	IAV_DRAM_MASK = PAGE_ALIGN(MASK_TOTAL_SIZE),

	IAV_DRAM_CMD_SYNC = PAGE_ALIGN(CMD_SYNC_TOTAL_SIZE),
	IAV_DRAM_CMD_STREAM_SYNC = PAGE_ALIGN(CMD_STREAM_SYNC_TOTAL_SIZE),

	IAV_DRAM_STREAM = PAGE_ALIGN(ENC_LIST_TOTAL_SIZE),
	IAV_DRAM_CANVAS_SYNC = PAGE_ALIGN(CANVAS_LIST_TOTAL_SIZE),
	IAV_RSV_MULTI_CHAN = PAGE_ALIGN(MULTI_CHAN_TOTAL_SIZE),
	IAV_DRAM_MULTI_CHAN = PAGE_ALIGN(MULTI_CHAN_TOTAL_SIZE),
	IAV_DRAM_DSP_CV = PAGE_ALIGN(DSP_CV_SHARE_BUF_SIZE),
	IAV_DRAM_IMG_NN = PAGE_ALIGN(IAV_MEM_IMG_NN_BUF_SIZE),
	IAV_DRAM_CUSTOM_SEI = PAGE_ALIGN(CUSTOM_SEI_BUFFER_SIZE),
	IAV_DRAM_FUSION = PAGE_ALIGN(FUSION_CLUT_BUFFER_SIZE),
	IAV_DRAM_HPT = PAGE_ALIGN(HWARP_PADDING_TABLE_MEM_SIZE * CONFIG_AMBARELLA_MAX_CHANNEL_NUM),

	IAV_DRAM_MAX = IAV_DRAM_BLUR + IAV_DRAM_ARB_BLUR + IAV_DRAM_H26X_SCALELIST + IAV_DRAM_MULTI_COLOR_MASK + \
		IAV_DRAM_TML_FUSION + IAV_DRAM_INT_BSB + IAV_DRAM_BSB + IAV_DRAM_USR + IAV_DRAM_MV + IAV_DRAM_STAT + \
		IAV_DRAM_OVERLAY + IAV_DRAM_CANVAS_OVERLAY + IAV_DRAM_QPM + IAV_DRAM_WARP + IAV_DRAM_QUANT + \
		IAV_DRAM_IMG + IAV_DRAM_MASK + IAV_DRAM_MULTI_CHAN + IAV_DRAM_CMD_SYNC * 2 + IAV_DRAM_CMD_STREAM_SYNC + \
		IAV_DRAM_DEC_BSB + IAV_DRAM_DSP_CV + IAV_DRAM_IMG_NN + IAV_DRAM_CUSTOM_SEI + \
		IAV_DRAM_YUV_REMAP + IAV_DRAM_SMOOTH_BLUR + IAV_DRAM_ARB_SMOOTH_BLUR + IAV_DRAM_OF_NN,
} IAV_DRAM;

/* layout of IAV_PART_IAV_RSV */
#define IAV_RSV_WARP_CTRL_NUM		(16)
#define IAV_RSV_OF_NN_CTRL_NUM		(16)
#define IAV_RAW_ENC_CMD_QUEUE_LENGTH	(2)
#define IAV_AISP_RAW_ENC_CMD_QUEUE_LENGTH	(10)
#define IAV_NN_RAW_ENC_CMD_QUEUE_LENGTH	(6)
#define IAV_CMD_DEFAULT_MAX_NUM_IN_BATCH	(4)
/* Need to prepare AISP cmd for each NN, such as 3 AISP cmd for 1080p case, 5 AISP cmd for 4K case */
#define IAV_CMD_AISP_MAX_NUM_IN_BATCH		(IAV_AISP_NN_TYPE_TOTAL_NUM)
#define IAV_CMD_QUEUE_LENGTH_PER_VIN		(IAV_CMD_DEFAULT_MAX_NUM_IN_BATCH + IAV_CMD_AISP_MAX_NUM_IN_BATCH)
#define IAV_CMD_NUM_VIN_BATCH		(CONFIG_AMBARELLA_MAX_CHANNEL_NUM * IAV_CMD_QUEUE_LENGTH_PER_VIN)

#define IAV_MAX_VIRT_CHAN_NUM			(12)
#define IAV_RSV_STREAM_CFG			(PAGE_ALIGN(sizeof(enc_cfg_t) * IAV_MAX_ENCODE_STREAMS_NUM))
#define IAV_RSV_VIN_FOV_CFG			(PAGE_ALIGN(sizeof(vin_fov_cfg_t) * MAX_VIN_FOV_NUM * MAX_VIN_NUM))
#define IAV_RSV_VIN_COMPAND_CFG		(PAGE_ALIGN(sizeof(u16) * COMP_LUT_ENTRY_NUM) * VIN_INSTANCES)
#define IAV_RSV_VIN_DECOMPAND_CFG	(PAGE_ALIGN(sizeof(u32) * DECOMP_LUT_ENTRY_NUM) * VIN_INSTANCES)
#define IAV_RSV_VIN_COMPAND_2ND_CFG		(PAGE_ALIGN(sizeof(u16) * COMP_LUT_ENTRY_NUM) * VIN_INSTANCES)
#define IAV_RSV_VIN_DECOMPAND_2ND_CFG	(PAGE_ALIGN(sizeof(u32) * DECOMP_LUT_ENTRY_NUM) * VIN_INSTANCES)
#define IAV_RSV_VIN_PAT_DEMUX_CFG	(PAGE_ALIGN(sizeof(pattern_demux_chan_cfg_t) * CONFIG_AMBARELLA_MAX_CHANNEL_NUM))
#define IAV_RSV_WARP_CTRL_CFG			(PAGE_ALIGN(sizeof(idsp_group_update_info_t)) * CONFIG_AMBARELLA_MAX_CHANNEL_NUM * IAV_RSV_WARP_CTRL_NUM)
#define IAV_RSV_BATCH_CMD_CFG		(PAGE_ALIGN(sizeof(DSP_CMD) * IAV_CMD_NUM_VIN_BATCH))
#define IAV_RSV_OF_NN_CTRL_CFG			(PAGE_ALIGN(sizeof(idsp_group_update_info_t)) * CONFIG_AMBARELLA_MAX_CHANNEL_NUM * IAV_RSV_OF_NN_CTRL_NUM)
#define IAV_RSV_CHAN_MAX_CFG_ALIGN			(128)
#define IAV_RSV_CHAN_MAX_CFG_SINGLE_SIZE	(ROUND_UP(sizeof(cmd_dsp_iproc_chan_max_cfg_t), IAV_RSV_CHAN_MAX_CFG_ALIGN))
#define IAV_RSV_CHAN_MAX_CFG		(PAGE_ALIGN(IAV_RSV_CHAN_MAX_CFG_SINGLE_SIZE * (CONFIG_AMBARELLA_MAX_CHANNEL_NUM + IAV_MAX_VIRT_CHAN_NUM)))
#define IAV_RSV_FISHI_REGION_CFG	(PAGE_ALIGN(sizeof(iproc_fishi_region_t) * (IAV_MAX_CHANNEL_NUM) * MAX_NUM_WARP_AREAS * IAV_RSV_WARP_CTRL_NUM))
#define IAV_RSV_FISHI_PREV_CFG		(PAGE_ALIGN(sizeof(iproc_fishi_region_prev_t) * (IAV_MAX_CHANNEL_NUM) * MAX_NUM_WARP_AREAS * IAV_RSV_WARP_CTRL_NUM))
#define IAV_RSV_IPROC_CANVAS_CFG			(PAGE_ALIGN(sizeof(DSP_CMD) * IPROC_MAX_SRCBUF_NUM))

#define IAV_CHAN_EXT_MEM_CFG_NUM		(8)
#define IAV_RSV_EXT_MEM_CFG			(PAGE_ALIGN(sizeof(ext_mem_desc_t) * IAV_CHAN_EXT_MEM_CFG_NUM * CONFIG_AMBARELLA_MAX_CHANNEL_NUM))
#define IAV_EXT_BUF_CFG_MAX_NUM			(16)
#define IAV_EXT_BUF_CFG_SIZE			(4)
#define IAV_EXT_BUF_CFG_SRCBUF_SINGLE_CHAN_SIZE		(IAV_EXT_BUF_CFG_SIZE * IAV_SRCBUF_NUM * IAV_EXT_BUF_CFG_MAX_NUM)
#define IAV_EXT_BUF_CFG_SRCBUF_TOTAL_SIZE		(PAGE_ALIGN(IAV_EXT_BUF_CFG_SRCBUF_SINGLE_CHAN_SIZE * CONFIG_AMBARELLA_MAX_CHANNEL_NUM))
#define IAV_EXT_BUF_CFG_PYRAMID_SINGLE_CHAN_SIZE		(IAV_EXT_BUF_CFG_SIZE * 1 * IAV_EXT_BUF_CFG_MAX_NUM)
#define IAV_EXT_BUF_CFG_PYRAMID_TOTAL_SIZE		(PAGE_ALIGN(IAV_EXT_BUF_CFG_PYRAMID_SINGLE_CHAN_SIZE * CONFIG_AMBARELLA_MAX_CHANNEL_NUM))
#define IAV_EXT_BUF_CFG_RAW_CE_SINGLE_VIN_SIZE		(IAV_EXT_BUF_CFG_SIZE * 1 * IAV_MAX_MF_BUF_NUM)
#define IAV_EXT_BUF_CFG_RAW_CE_TOTAL_SIZE		(PAGE_ALIGN(IAV_EXT_BUF_CFG_RAW_CE_SINGLE_VIN_SIZE * VIN_CONTROLLER_NUM))
#define IAV_EXT_BUF_CFG_RAW_LOW_CE_SINGLE_VIN_SIZE	(IAV_EXT_BUF_CFG_SIZE * 1 * IAV_MAX_MF_BUF_NUM)
#define IAV_RSV_EXT_BUF_RAW_LOW_CE_TOTAL_SIZE		(PAGE_ALIGN(IAV_EXT_BUF_CFG_RAW_LOW_CE_SINGLE_VIN_SIZE * VIN_CONTROLLER_NUM))
#define IAV_EXT_BUF_CFG_RAW_SINGLE_VIN_SIZE		(IAV_EXT_BUF_CFG_SIZE * 2 * IAV_MAX_MF_BUF_NUM)
#define IAV_EXT_BUF_CFG_RAW_TOTAL_SIZE		(PAGE_ALIGN(IAV_EXT_BUF_CFG_RAW_SINGLE_VIN_SIZE * VIN_CONTROLLER_NUM))
#define IAV_VIN_CFG_SIZE			(256)		/* Max size for struct vin_dsp_config */
#define IAV_RSV_VIN_DSP_CFG			(PAGE_ALIGN(IAV_VIN_CFG_SIZE * VIN_CONTROLLER_NUM))
#define IAV_RSV_IMG_SCALE_CFG_SIZE			(sizeof(iproc_scale_job_t))
#define IAV_RSV_IMG_SCALE_CFG			(PAGE_ALIGN(IAV_RSV_IMG_SCALE_CFG_SIZE * IAV_IMG_SCALE_Q_DEPTH_MAX))
#define IAV_VOUT_DISP_CFG_SIZE		(1024)		/* Max size for vout_display_config_t */
#define IAV_RSV_VOUT_DISPLAY_CFG	(PAGE_ALIGN(IAV_VOUT_DISP_CFG_SIZE * VOUT_NUM))
#define IAV_VOUT_DVE_CFG_SIZE		(1024)		/* Max size for vout_dve_config_t */
#define IAV_RSV_VOUT_DVE_CFG		(PAGE_ALIGN(IAV_VOUT_DVE_CFG_SIZE * VOUT_NUM))
#define IAV_VOUT_OSD_CLUT_CFG_SIZE	(1024)		/* 256 colors * 4 bytes per color */
#define IAV_RSV_VOUT_OSD_CLUT_CFG	(PAGE_ALIGN(IAV_VOUT_OSD_CLUT_CFG_SIZE * VOUT_NUM))
#define IAV_RSV_EFM_EXT_MEM_SINGLE_CFG		(sizeof(u32) * 2 * IAV_EFM_MAX_BUF_NUM)	// 2 for YUV
#define IAV_RSV_EFM_EXT_MEM_CFG		(PAGE_ALIGN(IAV_RSV_EFM_EXT_MEM_SINGLE_CFG * MAX_CANVAS_NUM))
#define IAV_RSV_EFM_EXT_REL_SINGLE_BUF_SIZE		(sizeof(ext_mem_rel_info_t))
#define IAV_RSV_EFM_EXT_REL_BUF_SIZE		(PAGE_ALIGN(IAV_RSV_EFM_EXT_REL_SINGLE_BUF_SIZE * IAV_MAX_EFM_REL_BUF_NUM))
#define IAV_RSV_CHAN_GRP_CFG_SIZE	(PAGE_ALIGN(sizeof(DSP_CMD) * IPROC_MAX_GRP_NUM))

#define IAV_CANVAS_BATCH_CMD_TOGGLE_NUM		(16)
#define IAV_CANVAS_BATCH_DSP_CMD_NUM		(3 * IAV_STREAM_MAX_NUM_ALL) /* up to 60 cmd per canvas at a time */
#define IAV_CANVAS_BATCH_CMD_PART_SIZE		(sizeof(DSP_CMD) * IAV_CANVAS_BATCH_DSP_CMD_NUM)
#define IAV_CANVAS_BATCH_CMD_SINGLE_SIZE	(IAV_CANVAS_BATCH_CMD_PART_SIZE * IAV_CANVAS_BATCH_CMD_TOGGLE_NUM)
#define IAV_CANVAS_BATCH_CMD_TOTAL_SIZE		(PAGE_ALIGN(IAV_CANVAS_BATCH_CMD_SINGLE_SIZE * MAX_CANVAS_NUM))

#define IAV_RSV_DEC_CFG				(sizeof(dec_cfg_t))
#define IAV_RSV_DEC_CFG_SIZE			(PAGE_ALIGN(IAV_RSV_DEC_CFG * IAV_MAX_DECODER_NUMBER))
#define IAV_SCALE_PRIVACY_MASK_SIZE	(1024)		/* 512 / 8 * 16 */
#define IAV_RSV_SCALE_PRIVACY_MASK_CFG_SIZE	(PAGE_ALIGN(IAV_SCALE_PRIVACY_MASK_SIZE * 2))	/* 2 PMs, one is 0x00, the other is 0xFF. */

#define IAV_ARB_BLEND_CFG_TOGGLE_NUM		(8)
#define IAV_ARB_BLEND_MSG_BUF_NUM			(8)	/* 8, the value must be power of 2. */
#define IAV_RSV_ARB_BLEND_MSG_SIZE	(sizeof(fishi_blend_info_t) * IAV_ARB_BLEND_MSG_BUF_NUM)
#define IAV_RSV_ARB_BLEND_CFG_SIZE	(sizeof(iproc_fishi_blend_job_t) * IAV_MAX_BLEND_AREA_NUM * IAV_ARB_BLEND_CFG_TOGGLE_NUM)
#define IAV_RSV_ARB_BLEND_SIZE	(IAV_RSV_ARB_BLEND_CFG_SIZE + IAV_RSV_ARB_BLEND_MSG_SIZE)

#define IAV_RSV_IVIN_DBUF_MAX_CFG_SIZE		(ROUND_UP(sizeof(cmd_dsp_ivin_dbuf_max_cfg_t), IAV_VIN_DBUF_CFG_SIZE_ALIGN) * VIN_CONTROLLER_NUM)
#define IAV_RSV_IVIN_FLOW_MAX_CFG_SIZE		(ROUND_UP(sizeof(cmd_dsp_ivin_flow_max_cfg_t), IAV_VIN_DBUF_CFG_SIZE_ALIGN) * VIN_CONTROLLER_NUM)
#define IAV_RSV_EFM_RECT_TOGGLE_NUM			(4)
#define IAV_RSV_EFM_RECT_PART_SIZE			(sizeof(rect_info_t) * IAV_EFM_RECT_NUM)
#define IAV_RSV_EFM_RECT_SINGLE_SIZE		(IAV_RSV_EFM_RECT_PART_SIZE * IAV_RSV_EFM_RECT_TOGGLE_NUM)
#define IAV_RSV_EFM_RECT_CFG_SIZE			(PAGE_ALIGN(IAV_RSV_EFM_RECT_SINGLE_SIZE * IAV_STREAM_MAX_NUM_ALL))
#define IAV_MAX_BUF_NUM_SINGLE_CANVAS		(20)
#define IAV_RSV_CANVAS_BLUR_RECT_TOGGLE_NUM		(4)
#define IAV_RSV_CANVAS_BLUR_RECT_PART_SIZE		(sizeof(rect_info_t) * IAV_MAX_BUF_NUM_SINGLE_CANVAS)
#define IAV_RSV_CANVAS_BLUR_RECT_SINGLE_SIZE		(IAV_RSV_CANVAS_BLUR_RECT_PART_SIZE * IAV_RSV_CANVAS_BLUR_RECT_TOGGLE_NUM)
#define IAV_RSV_CANVAS_BLUR_RECT_CFG_SIZE		(PAGE_ALIGN(IAV_RSV_CANVAS_BLUR_RECT_SINGLE_SIZE * MAX_CANVAS_NUM))
#define IAV_RSV_FISHI_AREA_MAX_CFG_SIZE     (PAGE_ALIGN(sizeof(iproc_fishi_max_region_info_t) * MAX_NUM_WARP_AREAS * CONFIG_AMBARELLA_MAX_CHANNEL_NUM))
#define IAV_RSV_MRD_CTRL_NUM				(16)
#define IAV_RSV_MRD_REGION_CFG				(PAGE_ALIGN(sizeof(iproc_fishi_region_t) * (IAV_MAX_CHANNEL_NUM) * MAX_NUM_DPTZ_AREAS * IAV_RSV_MRD_CTRL_NUM))
#define IAV_RSV_MRD_PREV_CFG				(PAGE_ALIGN(sizeof(iproc_fishi_region_prev_t) * (IAV_MAX_CHANNEL_NUM) * MAX_NUM_DPTZ_AREAS * IAV_RSV_MRD_CTRL_NUM))
#define IAV_IDSP_SYNC_CMD_HSK_TOGGLE_NUM	(16)
#define IAV_CMD_NUM_IDSP_SYNC_BATCH			(CONFIG_AMBARELLA_MAX_CHANNEL_NUM * IAV_IDSP_SYNC_CMD_HSK_TOGGLE_NUM)
#define IAV_RSV_IDSP_SYNC_BATCH_CMD_CFG		(PAGE_ALIGN(sizeof(DSP_CMD) * IAV_CMD_DEFAULT_MAX_NUM_IN_BATCH * IAV_CMD_NUM_IDSP_SYNC_BATCH))

/*
 * EFM frame sync command memory configuration, which uses srcbuf group cmd's batch cmd to
 * implement real-time encode cmd sync and postp(overlay/blur/yuvremap) cmd sync.
 * layout:	|--EFM frame sync--------------------|
 *			|     stream 0:                      |
 *			|          Apply cmd                 |
 *			|          real-time encode cmd pool |
 *			|          postp cmd pool            |
 *			|     stream 1:                      |
 *			|          Apply cmd                 |
 *			|          real-time encode cmd pool |
 *			|          postp cmd pool            |
 *			|     ......                         |
 *			|     stream N:                      |
 *			|          Apply cmd                 |
 *			|          real-time encode cmd pool |
 *			|          postp cmd pool            |
 *			|------------------------------------|
 * For Apply cmd, it follows below layout:
 *			|  Apply_cmd_0  |  Apply_cmd_1  |  ..  |  Apply_cmd_(toggle_num - 1)  |
 * For real-time encode cmd pool, it follows below layout:
 *			|   enc_cmd_0   |   enc_cmd_1   |  ..  |   enc_cmd_(toggle_num - 1)   |
 * For postp cmd pool, it follows below layout:
 *			|  postp_cmd_0  |  postp_cmd_1  |  ..  |  postp_cmd_(toggle_num - 1)  |
 */
typedef enum {
	IAV_EFM_SYNC_APPLY_CMD_TOGGLE_NUM = 8,
	IAV_EFM_SYNC_APPLY_CMD_SINGLE_SIZE = (DSP_CMD_SIZE * IAV_EFM_SYNC_APPLY_CMD_TOGGLE_NUM),

	IAV_EFM_SYNC_CFG_CMD_TOGGLE_NUM = 32,
	IAV_EFM_SYNC_CFG_CMD_TYPE_ENC = 0,
	IAV_EFM_SYNC_CFG_CMD_TYPE_POSTP = 1,
	IAV_EFM_SYNC_CFG_CMD_TYPE_NUM = 2,
	IAV_EFM_SYNC_CFG_CMD_SINGLE_SIZE = (DSP_CMD_SIZE * IAV_EFM_SYNC_CFG_CMD_TOGGLE_NUM),
	IAV_EFM_SYNC_CFG_CMD_PART_SIZE = (IAV_EFM_SYNC_CFG_CMD_SINGLE_SIZE * IAV_EFM_SYNC_CFG_CMD_TYPE_NUM),

	IAV_EFM_FRAME_SYNC_CMD_SINGLE_SIZE = (IAV_EFM_SYNC_APPLY_CMD_SINGLE_SIZE + IAV_EFM_SYNC_CFG_CMD_PART_SIZE),
	IAV_EFM_FRAME_SYNC_CMD_TOTAL_SIZE = (PAGE_ALIGN(IAV_EFM_FRAME_SYNC_CMD_SINGLE_SIZE * IAV_STREAM_MAX_NUM_ALL)),
} IAV_EFM_CMD_SYNC_PARAMS;

#define IAV_RSV_BUF_SIZE			(IAV_RSV_MULTI_CHAN + IAV_RSV_STREAM_CFG + \
		IAV_RSV_VIN_FOV_CFG + IAV_RSV_VIN_COMPAND_CFG + IAV_RSV_VIN_DECOMPAND_CFG + \
		IAV_RSV_VIN_COMPAND_2ND_CFG + IAV_RSV_VIN_DECOMPAND_2ND_CFG + IAV_RSV_VIN_PAT_DEMUX_CFG + \
		IAV_RSV_BATCH_CMD_CFG + IAV_RSV_CHAN_MAX_CFG + IAV_RSV_FISHI_REGION_CFG + IAV_RSV_FISHI_PREV_CFG + \
		IAV_RSV_EXT_MEM_CFG + IAV_EXT_BUF_CFG_SRCBUF_TOTAL_SIZE + IAV_EXT_BUF_CFG_PYRAMID_TOTAL_SIZE + \
		IAV_EXT_BUF_CFG_RAW_CE_TOTAL_SIZE + IAV_RSV_EXT_BUF_RAW_LOW_CE_TOTAL_SIZE + IAV_EXT_BUF_CFG_RAW_TOTAL_SIZE + \
		IAV_RSV_VIN_DSP_CFG + IAV_RSV_IMG_SCALE_CFG + IAV_RSV_WARP_CTRL_CFG + IAV_RSV_VOUT_DISPLAY_CFG * 4 + \
		IAV_RSV_VOUT_DVE_CFG + IAV_RSV_VOUT_OSD_CLUT_CFG + IAV_RSV_EFM_EXT_MEM_CFG + IAV_DRAM_STREAM * 3 + \
		+ IAV_DRAM_CANVAS_SYNC + IAV_DRAM_CMD_SYNC * 3 + IAV_DRAM_CMD_STREAM_SYNC + IAV_RSV_CHAN_GRP_CFG_SIZE + IAV_CANVAS_BATCH_CMD_TOTAL_SIZE + \
		IAV_RSV_DEC_CFG_SIZE + IAV_RSV_IPROC_CANVAS_CFG + IAV_RSV_SCALE_PRIVACY_MASK_CFG_SIZE + \
		IAV_RSV_ARB_BLEND_SIZE + IAV_RSV_IVIN_DBUF_MAX_CFG_SIZE + IAV_RSV_IVIN_FLOW_MAX_CFG_SIZE + \
		IAV_RSV_EFM_EXT_REL_BUF_SIZE + IAV_RSV_EFM_RECT_CFG_SIZE + IAV_EFM_FRAME_SYNC_CMD_TOTAL_SIZE + POSTP_SCALE_CMD_TOTAL_BUF_SIZE + \
		IAV_RSV_FISHI_AREA_MAX_CFG_SIZE + IAV_RSV_MRD_REGION_CFG + IAV_RSV_MRD_PREV_CFG + IAV_RSV_IDSP_SYNC_BATCH_CMD_CFG + \
		IAV_RSV_OF_NN_CTRL_CFG + IAV_RSV_CANVAS_BLUR_RECT_CFG_SIZE)

#define IAV_RSV_MULTI_CHAN_OFFSET			(0)
#define IAV_RSV_STREAM_CFG_OFFSET			(IAV_RSV_MULTI_CHAN)
#define IAV_RSV_VIN_FOV_CFG_OFFSET			(IAV_RSV_STREAM_CFG_OFFSET + IAV_RSV_STREAM_CFG)
#define IAV_RSV_VIN_COMPAND_CFG_OFFSET		(IAV_RSV_VIN_FOV_CFG_OFFSET + IAV_RSV_VIN_FOV_CFG)
#define IAV_RSV_VIN_DECOMPAND_CFG_OFFSET	(IAV_RSV_VIN_COMPAND_CFG_OFFSET + IAV_RSV_VIN_COMPAND_CFG)
#define IAV_RSV_VIN_COMPAND_2ND_CFG_OFFSET	(IAV_RSV_VIN_DECOMPAND_CFG_OFFSET + IAV_RSV_VIN_DECOMPAND_CFG)
#define IAV_RSV_VIN_DECOMPAND_2ND_CFG_OFFSET	(IAV_RSV_VIN_COMPAND_2ND_CFG_OFFSET + IAV_RSV_VIN_COMPAND_2ND_CFG)
#define IAV_RSV_VIN_PAT_DEMUX_CFG_OFFSET	(IAV_RSV_VIN_DECOMPAND_2ND_CFG_OFFSET + IAV_RSV_VIN_DECOMPAND_2ND_CFG)
#define IAV_RSV_WARP_CTRL_CFG_OFFSET		(IAV_RSV_VIN_PAT_DEMUX_CFG_OFFSET + IAV_RSV_VIN_PAT_DEMUX_CFG)
#define IAV_RSV_BATCH_CMD_OFFSET			(IAV_RSV_WARP_CTRL_CFG_OFFSET + IAV_RSV_WARP_CTRL_CFG)
#define IAV_RSV_CHAN_MAX_CFG_OFFSET			(IAV_RSV_BATCH_CMD_OFFSET + IAV_RSV_BATCH_CMD_CFG)
#define IAV_RSV_FISHI_REGION_CFG_OFFSET		(IAV_RSV_CHAN_MAX_CFG_OFFSET + IAV_RSV_CHAN_MAX_CFG)
#define IAV_RSV_FISHI_PREV_CFG_OFFSET		(IAV_RSV_FISHI_REGION_CFG_OFFSET + IAV_RSV_FISHI_REGION_CFG)
#define IAV_RSV_IPROC_CANVAS_OFFSET			(IAV_RSV_FISHI_PREV_CFG_OFFSET + IAV_RSV_FISHI_PREV_CFG)
#define IAV_RSV_EFM_EXT_REL_BUF_OFFSET		(IAV_RSV_IPROC_CANVAS_OFFSET + IAV_RSV_IPROC_CANVAS_CFG)
#define IAV_RSV_EXT_MEM_CFG_OFFSET			(IAV_RSV_EFM_EXT_REL_BUF_OFFSET + IAV_RSV_EFM_EXT_REL_BUF_SIZE)
#define IAV_RSV_EXT_BUF_SRCBUF_CFG_OFFSET	(IAV_RSV_EXT_MEM_CFG_OFFSET + IAV_RSV_EXT_MEM_CFG)
#define IAV_RSV_EXT_BUF_PYRAMID_CFG_OFFSET	(IAV_RSV_EXT_BUF_SRCBUF_CFG_OFFSET + IAV_EXT_BUF_CFG_SRCBUF_TOTAL_SIZE)
#define IAV_RSV_EXT_BUF_RAW_CE_CFG_OFFSET	(IAV_RSV_EXT_BUF_PYRAMID_CFG_OFFSET + IAV_EXT_BUF_CFG_PYRAMID_TOTAL_SIZE)
#define IAV_RSV_EXT_BUF_RAW_LOW_CE_CFG_OFFSET	(IAV_RSV_EXT_BUF_RAW_CE_CFG_OFFSET + IAV_EXT_BUF_CFG_RAW_CE_TOTAL_SIZE)
#define IAV_RSV_EXT_BUF_RAW_CFG_OFFSET		(IAV_RSV_EXT_BUF_RAW_LOW_CE_CFG_OFFSET + IAV_RSV_EXT_BUF_RAW_LOW_CE_TOTAL_SIZE)
#define IAV_RSV_VIN_DSP_CFG_OFFSET			(IAV_RSV_EXT_BUF_RAW_CFG_OFFSET + IAV_EXT_BUF_CFG_RAW_TOTAL_SIZE)
#define IAV_RSV_IMG_SCALE_CFG_OFFSET		(IAV_RSV_VIN_DSP_CFG_OFFSET + IAV_RSV_VIN_DSP_CFG)
#define IAV_RSV_VOUT_DISPLAY_CFG_OFFSET		(IAV_RSV_IMG_SCALE_CFG_OFFSET + IAV_RSV_IMG_SCALE_CFG)

#define IAV_RSV_VOUT_DISPLAY_V1_CFG_OFFSET		(IAV_RSV_VOUT_DISPLAY_CFG_OFFSET + IAV_RSV_VOUT_DISPLAY_CFG)
#define IAV_RSV_VOUT_DISPLAY_V2_CFG_OFFSET		(IAV_RSV_VOUT_DISPLAY_V1_CFG_OFFSET + IAV_RSV_VOUT_DISPLAY_CFG)
#define IAV_RSV_VOUT_DISPLAY_V3_CFG_OFFSET		(IAV_RSV_VOUT_DISPLAY_V2_CFG_OFFSET + IAV_RSV_VOUT_DISPLAY_CFG)
#define IAV_RSV_VOUT_DVE_CFG_OFFSET			(IAV_RSV_VOUT_DISPLAY_V3_CFG_OFFSET + IAV_RSV_VOUT_DISPLAY_CFG)

#define IAV_RSV_VOUT_OSD_CLUT_CFG_OFFSET	(IAV_RSV_VOUT_DVE_CFG_OFFSET + IAV_RSV_VOUT_DVE_CFG)
#define IAV_RSV_EFM_EXT_MEM_OFFSET			(IAV_RSV_VOUT_OSD_CLUT_CFG_OFFSET + IAV_RSV_VOUT_OSD_CLUT_CFG)
#define IAV_DRAM_NON_SYNC_ENC_LIST_OFFSET	(IAV_RSV_EFM_EXT_MEM_OFFSET + IAV_RSV_EFM_EXT_MEM_CFG)
#define IAV_DRAM_FRM_SYNC_ENC_LIST_OFFSET	(IAV_DRAM_NON_SYNC_ENC_LIST_OFFSET + IAV_DRAM_STREAM)
#define IAV_DRAM_IE_SYNC_ENC_LIST_OFFSET	(IAV_DRAM_FRM_SYNC_ENC_LIST_OFFSET + IAV_DRAM_STREAM)
#define IAV_DRAM_FRM_SYNC_CMD_OFFSET		(IAV_DRAM_IE_SYNC_ENC_LIST_OFFSET + IAV_DRAM_STREAM)
#define IAV_DRAM_CANVAS_SYNC_ENC_LIST_OFFSET	(IAV_DRAM_FRM_SYNC_CMD_OFFSET + IAV_DRAM_CANVAS_SYNC)

#define IAV_DRAM_STRM_SYNC_CMD_OFFSET		(IAV_DRAM_CANVAS_SYNC_ENC_LIST_OFFSET + IAV_DRAM_CMD_SYNC)
#define IAV_DRAM_IE_SYNC_CMD_OFFSET			(IAV_DRAM_STRM_SYNC_CMD_OFFSET + IAV_DRAM_CMD_STREAM_SYNC)
#define IAV_DRAM_STRM_CFG_OFFSET			(IAV_DRAM_IE_SYNC_CMD_OFFSET + IAV_DRAM_CMD_SYNC)
#define IAV_RSV_CHAN_GRP_CFG_OFFSET			(IAV_DRAM_STRM_CFG_OFFSET + IAV_DRAM_CMD_SYNC)
#define IAV_RSV_CANVAS_BATCH_CFG_OFFSET		(IAV_RSV_CHAN_GRP_CFG_OFFSET + IAV_RSV_CHAN_GRP_CFG_SIZE)
#define IAV_RSV_DEC_CFG_OFFSET			(IAV_RSV_CANVAS_BATCH_CFG_OFFSET + IAV_CANVAS_BATCH_CMD_TOTAL_SIZE)
#define IAV_RSV_SCALE_PRIVACY_MASK_CFG_OFFSET			(IAV_RSV_DEC_CFG_OFFSET + IAV_RSV_DEC_CFG_SIZE)
#define IAV_RSV_ARB_BLEND_CFG_OFFSET		(IAV_RSV_SCALE_PRIVACY_MASK_CFG_OFFSET + IAV_RSV_SCALE_PRIVACY_MASK_CFG_SIZE)

#define IAV_RSV_IVIN_DBUF_MAX_CFG_OFFSET	(IAV_RSV_ARB_BLEND_CFG_OFFSET + IAV_RSV_ARB_BLEND_SIZE)
#define IAV_RSV_IVIN_FLOW_MAX_CFG_OFFSET	(IAV_RSV_IVIN_DBUF_MAX_CFG_OFFSET + IAV_RSV_IVIN_DBUF_MAX_CFG_SIZE)
#define IAV_RSV_EFM_RECT_CFG_OFFSET			(IAV_RSV_IVIN_FLOW_MAX_CFG_OFFSET + IAV_RSV_IVIN_FLOW_MAX_CFG_SIZE)
#define IAV_RSV_EFM_FRAME_SYNC_CFG_OFFSET	(IAV_RSV_EFM_RECT_CFG_OFFSET + IAV_RSV_EFM_RECT_CFG_SIZE)
#define IAV_RSV_FISHI_AREA_MAX_CFG_OFFSET	(IAV_RSV_EFM_FRAME_SYNC_CFG_OFFSET + IAV_EFM_FRAME_SYNC_CMD_TOTAL_SIZE)
#define IAV_RSV_MRD_REGION_CFG_OFFSET		(IAV_RSV_FISHI_AREA_MAX_CFG_OFFSET + IAV_RSV_FISHI_AREA_MAX_CFG_SIZE)
#define IAV_RSV_MRD_PREV_CFG_OFFSET			(IAV_RSV_MRD_REGION_CFG_OFFSET + IAV_RSV_MRD_REGION_CFG)
#define IAV_RSV_IDSP_SYNC_BATCH_CMD_OFFSET	(IAV_RSV_MRD_PREV_CFG_OFFSET + IAV_RSV_MRD_PREV_CFG)
#define IAV_RSV_POSTP_IMG_SCALE_CFG_OFFSET	(IAV_RSV_IDSP_SYNC_BATCH_CMD_OFFSET + IAV_RSV_IDSP_SYNC_BATCH_CMD_CFG)
#define IAV_RSV_OF_NN_CTRL_CFG_OFFSET		(IAV_RSV_POSTP_IMG_SCALE_CFG_OFFSET + POSTP_SCALE_CMD_TOTAL_BUF_SIZE)
#define IAV_RSV_CANVAS_BLUR_RECT_CFG_OFFSET		(IAV_RSV_OF_NN_CTRL_CFG_OFFSET + IAV_RSV_OF_NN_CTRL_CFG)
#define IAV_RSV_FINAL_CFG_OFFSET			(IAV_RSV_CANVAS_BLUR_RECT_CFG_OFFSET + IAV_RSV_CANVAS_BLUR_RECT_CFG_SIZE)

#define IAV_RSV_CFG_OFFSET_START	(IAV_RSV_STREAM_CFG_OFFSET)
#define IAV_RSV_CFG_OFFSET_END		(IAV_RSV_FINAL_CFG_OFFSET)

#endif	// __IAV_CONFIG_H__
